### ISSUE TITLE
Response field key should use raw key name

### ISSUE THREAD

**Issue by fundon** [nodejitsu/node-http-proxy#1029]
See https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-outgoing.js#L83-L89.

The `proxyRes.headers` are in lowercase. But the raw headers is not.
So I thought that we should use `proxyRes.rawHeaders` instead of `proxyRes.headers`.

**Comment by fragsalat** [comment]
:+1:

**Comment by oleynikd** [comment]
👍

**Comment by jcrugzz** [comment]
Fixed in 1.16.0

**Comment by pachirel** [comment]
I added `preserveHeaderKeyCase` option. If the option is enabled, you can get raw key name. #1104
