### ISSUE TITLE
X-Sendfile/X-Accel-Redirect support

### ISSUE THREAD

**Issue by johnae** [nodejitsu/node-http-proxy#106]
I've been trying to implement something like this but I'm still a newbie when it comes to node and node-http-proxy. Basically, what I'd like to see in node-http-proxy is support for a more nginx-like x-accel-redirect. Nginx can not only send files from the local disk but also send them from another backend server. So you could in, say Rails, do:

headers['X-Accel-Redirect'] = '/some/file.mp4'
or even
headers['X-Accel-Redirect'] = 'http://myotherbackend.example.com:1234/some/file.mp4'

I guess node-http-proxy would have to support checking the headers returned from backend and if it contains X-Accel-Redirect (or perhaps X-Sendfile - or even something else) it would send that out instead. Something like that.

At first I thought perhaps a middleware could accomplish this but well, I'm a newbie, and couldn't figure out how. Then I cloned the source and started hacking on it... haven't got very far yet though.

We need this since we'd like to offload this stuff from Rails onto the frontends. We currently use nginx as our frontend but nginx has problems with http 1.1 to backends and we must absolutely have 1.1 to our backends(these are not rails backends). We also use node which we'd actually like to use as our frontend going forward.

**Comment by jcrugzz** [comment]
Closing, node core still does not have `sendFile`
