### ISSUE TITLE
getting Error: Cannot set deprecated header: connection with http2

### ISSUE THREAD

**Issue by nnIIInnjA** [nodejitsu/node-http-proxy#1069]
or how not to send connection header in request ?

**Comment by DaSchTour** [comment]
Same problem here. Tried to used BrowserSync Proxy with HTTP2. 😞

**Comment by Yugloocamai** [comment]
Ditto ^^ same problem, browsersync + HTTP2

**Comment by carloschneider** [comment]
+1
