### ISSUE TITLE
Set-Cookie headers do not get combined in 1.16

### ISSUE THREAD

**Issue by tomlagier** [nodejitsu/node-http-proxy#1101]
Minor version bump of http-proxy caused our Ember-cli app to only forward a single cookie from the back-end, rather than all cookies. I believe this is because of the rewrite to web-outgoing.js/writeHeaders.

```
 Set-Cookie: GOP_LOGIN=1001; Path=/; Domain=localhost
 Set-Cookie: GOP_ACCOUNT=1001; Path=/; Domain=localhost
 Set-Cookie: PLAY_SESSION="xxx"; Path=/
```

Gets turned into this in the response header:

```
Set-Cookie:GOP_ACCOUNT=1001; Path=/; Domain=localhost
```

**Comment by kriswill** [comment]
@jcrugzz @tomlagier this should be fixed now, please retest!

**Comment by jcrugzz** [comment]
Yes this should be fixed with the changes made by @kriswill. Will reopen if this is still a problem. My apologies for the trouble.
