### ISSUE TITLE
autoRewrite is broken in 1.16

### ISSUE THREAD

**Issue by apalchys** [nodejitsu/node-http-proxy#1103]
It seems the following commit introduces a bug and "autoRewite" doesn't work properly now:  https://github.com/nodejitsu/node-http-proxy/commit/4edbb62cc5881b20e7dae5e6240e693b03fd3609

Method [setRedirectHostRewrite ](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-outgoing.js#L71) changes "location" header, but [writeHeaders ](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-outgoing.js#L107) ignores it and uses `rawHeaders` instead of `headers`

**Comment by jcrugzz** [comment]
@apalchys could you give some more information on whats not working? what changed in the expectations? I apologize if all the conditions were not covered but the same logic is being run but is the value of the header not what is expected?

**Comment by apalchys** [comment]
@jcrugzz you can find more details in a PR opened by @pachirel https://github.com/nodejitsu/node-http-proxy/pull/1104

**Comment by pachirel** [comment]
I have not tried to reproduce this issue yet.
Any additional information are welcome. :)
2016年12月6日(火) 19:40 Andrei <notifications@github.com>:

**Comment by apalchys** [comment]
@pachirel  your PR looks good and should fix autoRewrite because it doesn't overwrite header value. thanks.

**Comment by pachirel** [comment]
@apalchys 1.16.2 is available. please update and check your app. thanks to @jcrugzz.

**Comment by myfancypants** [comment]
I don't know if this would be the right place for feedback but in lib/http-proxy/passes/web-outgoing.js
```
res.setHeader('Set-Cookie', setCookies.length === 1 ? setCookies[0] : setCookies);
```

from 1.16.1 prior to the roll back was a breaking change. Our tooling was expecting a consistent array of cookies returned. The return of a string or an array was causing everything to break. Working locally and simply returning

```
res.setHeader('Set-Cookie', setCookies);
```

got us back up and operational.

I don't know if this impacts autoRewrite specifically, but figured I could provide some feedback on my own investigations into the matter

**Comment by apalchys** [comment]
@pachirel it works now. thanks a lot!
