### ISSUE TITLE
How is it possible to have multiple HTTPS proxies

### ISSUE THREAD

**Issue by SET001** [nodejitsu/node-http-proxy#1118]
How is it possible to have multiple HTTPS -> HTTP proxies?

Seems like I can't do something like in this example for HTTP -> HTTP:

```
http.createServer(function(req, res) {
  proxy.web(req, res, { target: 'http://mytarget.com:8080' });
});
```
because for each server instance I should provide certificate.

I found `SNICallback` in `https` options but I don't know is it right approach and how to use it.

**Comment by jcrugzz** [comment]
@SET001 this technically doesnt have anything to do with `node-http-proxy`. This has to do with handling multiple SSL certs from a single `https` server. You are correct in that using `SNICallback` is the right approach. You should search for more examples and try it out yourself. I found [this](http://blog.sammauldin.com/configuring-https-with-node-js-startssl-and-sni/) blog post and improved their example below.


```js
var https = require("https");
var tls = require("tls");
var constants = require("constants");
var fs = require("fs");
 
var passphrase = "Your password here";
var certificates = {
  "foo.com": { key: fs.readFileSync("fookey.pem"), cert: fs.readFileSync("foocert.pem") },
  "bar.com": { key: fs.readFileSync("barkey.pem"), cert: fs.readFileSync("barcert.pem") }
};
https.createServer({
    key: fs.readFileSync(__dirname + "/yourkey.pem"),
    cert: fs.readFileSync(__dirname + "/yourcert.pem"),
    passphrase: passphrase,
    SNICallback: function(servername, cb) {
        
        if (certificates[servername]) {
            var ctx = tls.createSecureContext(Object.assign({ passphrase}, certificates[servername]});
            // Compatibility with old versions of node
            if (cb) {
                cb(null, ctx);
            } else {
                return ctx;
            }
        }
    }
}, function(req, res) {
    res.end("Hello, SSL World!");
}).listen(443, function() {
    console.log("SSL Proxy listening on port 443");
});
```

**Comment by SET001** [comment]
I guess it has to do with `node-http-proxy` because I need to proxy multiple sub-domain calls to multiple servers running each on different ports. Something like this:

https://a.foo.com -> 127.0.0.1:3000
https://b.foo.com -> 127.0.0.1:3001
https://c.foo.com -> 127.0.0.1:3002

also I have a certificates for each of this domains. `SNICallback` will be called each time new connection to any of this sub-domains appears and I don't get how to proxy that connection to appropriate local server.

**Comment by jcrugzz** [comment]
A * based cert would make this easier ;) but doesnt matter either way. @SET001 check out the documentation as it gives examples of this. The proper cert will be handled by the SNICallback. You need to then proxy to a different `target` based on the `req.headers.host`. You can store a them similar to the certs above.

```js
var targets = {
  'a.foo.com': 'http://127.0.0.1:3000'
};
```

If you have anymore questions please ask on Stackoverflow or somewhere similar. If you find a bug or issue with `http-proxy` please feel free to open a new issue. Have fun :)

**Comment by SET001** [comment]
What I still can't understand is that I have few `*.key`/`*.cer` files for all subdomains which i get from `letsencrypt.org`  and which I will use in `SNICallback` like in your code. But I also should put one pair to `https.createServer`. What certificates should it be?

I have also created [question](http://stackoverflow.com/questions/41311391/how-is-it-possible-to-have-multiple-https-proxies) on StackOverflow but with no responses. So for now, you are the only one helping  me to figure out all this hell, for which I am very grateful to you.

**Comment by RONTheCookie** [comment]
@SET001 Have you figured this out yet? I'm in the same situation right now

**Comment by mingwiki** [comment]
> @SET001 this technically doesnt have anything to do with `node-http-proxy`. This has to do with handling multiple SSL certs from a single `https` server. You are correct in that using `SNICallback` is the right approach. You should search for more examples and try it out yourself. I found [this](http://blog.sammauldin.com/configuring-https-with-node-js-startssl-and-sni/) blog post and improved their example below.
> 
> ```js
> var https = require("https");
> var tls = require("tls");
> var constants = require("constants");
> var fs = require("fs");
>  
> var passphrase = "Your password here";
> var certificates = {
>   "foo.com": { key: fs.readFileSync("fookey.pem"), cert: fs.readFileSync("foocert.pem") },
>   "bar.com": { key: fs.readFileSync("barkey.pem"), cert: fs.readFileSync("barcert.pem") }
> };
> https.createServer({
>     key: fs.readFileSync(__dirname + "/yourkey.pem"),
>     cert: fs.readFileSync(__dirname + "/yourcert.pem"),
>     passphrase: passphrase,
>     SNICallback: function(servername, cb) {
>         
>         if (certificates[servername]) {
>             var ctx = tls.createSecureContext(Object.assign({ passphrase}, certificates[servername]}));
>             // Compatibility with old versions of node
>             if (cb) {
>                 cb(null, ctx);
>             } else {
>                 return ctx;
>             }
>         }
>     }
> }, function(req, res) {
>     res.end("Hello, SSL World!");
> }).listen(443, function() {
>     console.log("SSL Proxy listening on port 443");
> });
> ```

Hello, Could you tell me how to proxy Websocket in https.createServer with same tcp port? http-proxy is cool, but no SNICallback, https is cool, but no websocket.

**Comment by FX-HAO** [comment]
In my case, for local development, I'm using `mkcert` to generate self-signed certificates for multiple domains.
After researching it for a while, I finally work this out. For your reference

```
function getCredentialsContext(cer){
    return tls.createSecureContext({
        key:  fs.readFileSync(path.join(RootPath, 'certs', cer + '-key.pem')),
        cert: fs.readFileSync(path.join(RootPath, 'certs', cer + '.pem'))
    }).context;
}

var certs = {
    "abc.com":  getCredentialsContext("abc.com"),
    "def.com": getCredentialsContext("def.com")
};

const options = {
    ssl: {
        SNICallback: function(hostname, cb){
            var ctx = certs[hostname];
            // Compatibility with old versions of node
            if (cb) {
                cb(null, ctx);
            } else {
                return ctx;
            }

            return certs[hostname];
        }
    },
    hostnameOnly: true,
    router: {
        'abc.com':  '127.0.0.1:1080',
        'def.com': '127.0.0.1:1080'
    },
    target: {
        host: 'localhost',
        port: 1080
    }
};
httpProxy.createServer(options).listen(443);
```

**Comment by Marc477** [comment]
Here's a nice flexible way to do it

`const fs = require('fs');
const tls = require('tls');
const http = require('http');
const https = require('https');
const httpProxy = require('http-proxy');

const http_port = 80;
const https_port = 443;
const allow_http = true;
const allow_https = true;

const servers = {
	"mydomain1.com": {
		target_http: "http://127.0.0.1:5111",
		target_https: "https://127.0.0.1:5112",
		key: "/path/to/privkey.pem",
		cert: "/path/to/cert.pem",
		ca: "/path/to/chain.pem"
	},
	"mydomain2.com": {
		target_http: "http://127.0.0.1:5111",
		target_https: "https://127.0.0.1:5112",
		key: "/path/to/privkey.pem",
		cert: "/path/to/cert.pem",
		ca: "/path/to/chain.pem"
	},
	"mydomain3.com": {
		target_http: "http://127.0.0.1:5444",
		target_https: "https://127.0.0.1:5445",
		key: "/path/to/privkey.pem",
		cert: "/path/to/cert.pem",
		ca: "/path/to/chain.pem"
	},
	
}

//Read SSL
for (var host in servers) {
	var server = servers[host];
	if(server.cert)
	{
		server.ssl = {
			key: fs.readFileSync(server.key),
			ca: fs.readFileSync(server.ca),
			cert: fs.readFileSync(server.cert),
		}
		server.context = tls.createSecureContext(server.ssl);
	}
}

//Proxy Server
var proxy = httpProxy.createProxyServer({});

var GetSslContext = function(host, cb)
{
	var server = servers[host];
	if (server && server.context) {
		cb(null, server.context);
	}
}

var ProxyLogic = function(req, res) {
	
	var host = req.headers.host;
	var server = servers[host];
	if(server)
	{
	  var target = req.secure ? server.target_https : server.target_http;
	  var options = { target: target };
	  if(req.secure)
	  {
		  options.ssl = server.ssl;
		  options.secure = true;
	  }
	  proxy.web(req, res, options);
	}
};

//HTTP
if(allow_http){
	
    var httpServer = http.createServer(ProxyLogic);
    httpServer.listen(http_port, function () {
        console.log('http listening port %s', http_port);
    });
}

//HTTPS
if(allow_https) {
	
	var options  = { SNICallback: GetSslContext };
    var httpsServer = https.createServer(options, ProxyLogic);
    httpsServer.listen(https_port, function () {
        console.log('https listening port %s', https_port);
    });
}
`

**Comment by Marc477** [comment]
Here is my solution that support both http and https with multiple certs

Note, the https.createServer REQUIRES a certificate as parameter, even though its dynamically called with the SNICallback, so just put any of your site's certificate there as default cert. It will still dynamically use the correct one based on domain and will ignore the default one.

```
const fs = require('fs');
const tls = require('tls');
const http = require('http');
const https = require('https');
const httpProxy = require('http-proxy');

const http_port = 80;
const https_port = 443;
const allow_http = true;
const allow_https = true;

//Default SSL (required, just put any valid cert)
const https_key =  "/path/to/privkey.pem";
const https_cert = "/path/to/cert.pem";
const https_ca = "/path/to/chain.pem";

//Servers
const servers = {
	"mydomain1.com": {
		target_http: "127.0.0.1:5111",
		target_https: "127.0.0.1:5112",
		key: "/path/to/privkey.pem",
		cert: "/path/to/cert.pem",
		ca: "/path/to/chain.pem"
	},
	"mydomain2.com": {
		target_http: "127.0.0.1:5222",
		target_https: "127.0.0.1:5223",
		key: "/path/to/privkey.pem",
		cert: "/path/to/cert.pem",
		ca: "/path/to/chain.pem"
	},
	"mydomain3.com": {
		target_http: "127.0.0.1:5444",
		target_https: "127.0.0.1:5445",
		key: "/path/to/privkey.pem",
		cert: "/path/to/cert.pem",
		ca: "/path/to/chain.pem"
	},
	
}

//Read SSL
for (var host in servers) {
	var server = servers[host];
	if(server.cert)
	{
		server.ssl = {
			key: fs.readFileSync(server.key),
			ca: fs.readFileSync(server.ca),
			cert: fs.readFileSync(server.cert),
		}
		server.context = tls.createSecureContext(server.ssl);
	}
}

//Proxy Server
var proxy = httpProxy.createProxyServer({});

proxy.on('error', function (err, req, res) {
  res.writeHead(500);
  res.end('Proxy Error.');
});

var GetSslContext = function(host, cb)
{
	var server = servers[host];
	if (server && server.context) {
		cb(null, server.context);
	}
        else
        {
                cb("Invalid SSL");
        }
}

var ProxyLogic = function(req, res) {
	
	var host = req.headers.host;
	var server = servers[host];
	if(server)
	{
	     var secure = req.connection.encrypted;
	     var proto = secure ? 'https://' : 'http://';
	     var target = proto + (secure ? server.target_https : server.target_http);
	     var options = { target: target };
	     proxy.web(req, res, options);
	}
        else
	{
             res.writeHead(502);
             res.write('Invalid URL');
	     res.end();
	}
};

//HTTP
if(allow_http){
	
    var httpServer = http.createServer(ProxyLogic);
    httpServer.listen(http_port, function () {
        console.log('http listening port %s', http_port);
    });
}

//HTTPS
if(allow_https) {
	
    var options  = { 
		key: fs.readFileSync(https_key),
		cert: fs.readFileSync(https_cert),
		ca: fs.readFileSync(https_ca),
		SNICallback: GetSslContext 
    };

    var httpsServer = https.createServer(options, ProxyLogic);
    httpsServer.listen(https_port, function () {
        console.log('https listening port %s', https_port);
    });
}

```
