### ISSUE TITLE
HTTPS target throws `write EPROTO`

### ISSUE THREAD

**Issue by mars** [nodejitsu/node-http-proxy#1163]
Setting up a proxy to a Heroku app, whenever I set the target to an `HTTPS` URL, every connection fails with the classic `write EPROTO` errors:

```
Error: write EPROTO 139929235920768:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:769:
```

This happens locally on my macOS Sierra computer and when running on Heroku.

I've tried setting the certificate authority, but same error occurs:

```javascript
const proxy = httpProxy.createProxyServer({
  ssl: {
    // Heroku's CA location
    ca: fs.readFileSync('/usr/lib/ssl/certs/ca-certificates.crt', 'utf8')
  }
});
```

**Comment by mars** [comment]
Solved this 🌈

It seems that because the proxied host header no longer matches the target backend service, the SSL negotiation fails. The solution is to enabled `changeOrigin` which will rewrite the Host headers to match what the target expects!

```javascript
const proxy = httpProxy.createProxyServer({
  secure: true,
  changeOrigin: true
});
```

**Comment by darekf77** [comment]
This new agent property from
https://johnnyreilly.com/node-18-axios-and-unsafe-legacy-renegotiation-disabled
solved my problem
```ts
import https from 'https';
import * as crypto from 'crypto';
...
{
      target,
      ssl: {
        key: fse.readFileSync(this.serveKeyPath),
        cert: fse.readFileSync(this.serveCertPath),
      },
      agent: new https.Agent({
        // for self signed you could also add
        // rejectUnauthorized: false,
        // allow legacy server
        secureOptions: crypto.constants.SSL_OP_LEGACY_SERVER_CONNECT,
      }),
      secure: false,
      // followRedirects: true,
      // changeOrigin: true,
    } as httpProxy.ServerOptions
...
```
