### ISSUE TITLE
Is there anyone knows what does this statement do?

### ISSUE THREAD

**Issue by t-k-** [nodejitsu/node-http-proxy#1183]
https://github.com/nodejitsu/node-http-proxy/blob/c979ba9f2cbb6988a210ca42bf59698545496723/lib/http-proxy/index.js#L90

I have no idea, and in node console `require('eventemitter3')`  does not show a `call` function:
```
[Function: EventEmitter] prefixed: false, EventEmitter: [Circular] }
```

I am a javascript new bee, hope someone can help me.

**Comment by ultimate-tester** [comment]
Call is provided by Javascript itself, it's not a custom function:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call

I didn't have a look at the code at all, but it looks like it's calling the "constructor" of the EE3 prototype.

**Comment by t-k-** [comment]
@ultimate-tester Thank you for this comment, but I am still curious about why it needs to call the constructor of EE3 prototype, do you have an idea?

**Comment by jcrugzz** [comment]
@t-k- Its basically the same thing as 

```js
class Blah extends EE3 {
  constructor(opts) {
    super(opts)
  }
}
```
`EE3.call(this, opts)` ends up being equivalent to calling `super(opts)` above. This is all part of the inheritance dance of javascript before ES6 class syntax existed. 

You first copy all of the prototype methods from `EE3` to your desired object with something like [`util.inherits`](https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor). Then you call the constructor of the object you are inheriting from, in this case `EE3`. This finishes any potential initialization that the constructor provides so the inheritance is complete.
