### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by thiagobustamante** [nodejitsu/node-http-proxy#1185]
The last approved commit has more than 6 months. There are a lot of important Pull requests waiting for approval. Some of them fix critical bugs (like [this one](https://github.com/nodejitsu/node-http-proxy/pull/1182)).

**Comment by Tigge** [comment]
Perhaps someone in Nodejitsu (or at least former) - @3rd-Eden, @alexgorbatchev, @dscape, @indexzero, @jcrugzz, @Swaagie can let us know what the status is?

**Comment by vogrelord** [comment]
Maybe it's time to make a fork and merge all pull requests? Is there anyone clever enough to do thing like that?

**Comment by skerit** [comment]
Well, Nodejitsu was taken over by Godaddy. It seems like they no longer need this proxy server, so a fork would be a good idea.

**Comment by edmorley** [comment]
There are apparently 1400 NPM packages and 80,000+ GitHub repositories that have a dependency on this package:
https://github.com/nodejitsu/node-http-proxy/network/dependents

...so unless the fork is given ownership of the NPM package, switching everyone over is going to be a fair amount of effort.

**Comment by skerit** [comment]
Guess I spoke to soon, one of the owners said just yesterday he just doesn't have a lot of time and is looking for contributors: https://github.com/nodejitsu/node-http-proxy/issues/1211#issuecomment-344799313

**Comment by indexzero** [comment]
The active maintainers (@jcrugzz and I) appreciate the interest from the folks who are using `http-proxy` and have no plans to stop this work. 

Open Source is people folks. This project was _the first_ npm module I wrote in *2010*. I am literally a different person than when `require('http-proxy')` happened for the first time. 

Open Source for both of us has been a labor of love, and a lot has happened in the last couple years. I won't go into all the details but I will say that my dad's passing away was just one of these sorts of life events that happened for me. 

If you're interested in contributing your time please respond to this issue with how much time per month you would willing to contribute. 

> Closing as a duplicate of #1211.
