### ISSUE TITLE
http2 -> http1.1 - Header name must be a valid token

### ISSUE THREAD

**Issue by ronag** [nodejitsu/node-http-proxy#1201]
Sorry to open another http2 issue. However, it seems there are some incompatibility between HTTP2 and HTTP 1.1 headers, e.g. in HTTP2 we have the `:path` header which is not a valid header in HTTP 1.1 and would need to be transformed in some manner.

Is there any plans to add better HTTP2 support to node-http-proxy?

Also it would be nice if node-http-proxy could also support `http2.request`.

**Comment by ronag** [comment]
Possible solution?

```js
function toHTTPReq (req) {
  if (parseFloat(req) < 2.0) {
    return req
  }

  const headers = { ...req.headers }

  // https://http2.github.io/http2-spec/#rfc.section.8.1.2.3
  if (!headers.host) {
    headers.host = headers[':authority']
  }

  delete headers[':authority']
  delete headers[':method']
  delete headers[':path']
  delete headers[':scheme']

  return new Proxy(req, {
    get: (target, key) => key === 'headers' ? headers : target[key]
  })
}
```

**Comment by mintuhouse** [comment]
@ronag Is there a solution which works?

**Comment by ronag** [comment]
@mintuhouse not that I know of... I built a new npm library for http2 proxying.

**Comment by mylastore** [comment]
> @mintuhouse not that I know of... I built a new npm library for http2 proxying.

What is the library name link can you share it
