### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by tbc1** [nodejitsu/node-http-proxy#1211]
Right now, there are 302 open issues, 49 open pull requests and the last commit on the master branch was 10 months ago.

As nodejitsu was bought by GoDaddy a while ago, I wonder what the state of this repository is. Is it still maintained?

**Comment by ajimix** [comment]
Looks dead to me 👎

**Comment by dalgleish** [comment]
Would be nice if one of the 1,268 forks could emerge as a continuation.

**Comment by vogrelord** [comment]
How can we do it? I would like to participate in maintaining the project, but not sure what is correct way. Fork the repo and merge pull requests?

**Comment by jcrugzz** [comment]
Nothing here is dead, it has just gotten a bit stagnant. If you are interested in helping maintain this project please reach out to me over email. 

Current test coverage has made it tricky to merge PRs that seem harmless but change subtle proxy behavior. I haven’t had time to give this project the love it needs so help in this direction would go a long way in getting this project back on track.
