### ISSUE TITLE
Any plan of publishing a new release?

### ISSUE THREAD

**Issue by ryerh** [nodejitsu/node-http-proxy#1247]
https://github.com/nodejitsu/node-http-proxy/pull/1074 had fixed a bug which breaks our code. It's time to give a new release now (since the last release was 15 months ago).

**Comment by error0x404** [comment]
I don't think this is very active...

**Comment by jcrugzz** [comment]
New release went out 4 days ago. sorry for the wait @ryerh @error0x404
