### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by laureler** [nodejitsu/node-http-proxy#1253]
npm install http-proxy is error ,but i found its maybe rename node-http-proxy. you should npm install node-http-proxy

**Comment by jcrugzz** [comment]
@laureler the correct way to install is `npm install http-proxy --save` so you seem to have it right. Your failed installation may have to do with a network connection problem and not with the package itself. I would give it a try once you confirm you have a good connection to the registry you are trying to install from.

**Comment by laureler** [comment]
oh, thanks alot @jcrugzz
