### ISSUE TITLE
Setting Session

### ISSUE THREAD

**Issue by davutkara** [nodejitsu/node-http-proxy#1266]
How to set sessions correctly ?

Think that there is one proxy router then it routes 3 sub applications. 
I want to save a session on proxy router then send it sub applications.
Actually, I want to make one login system for 3 applications, when user logged in the any application, he accesses others without login.

Thanks.

**Comment by davutkara** [comment]
First try, I wanted to save session on proxy router. But there is a problem with response manipulation.

So, I tried to save session from sub application, and it's okay.

thx me.

**Comment by PaulDach** [comment]
Hello @davutkara , how did you manage this?

**Comment by davutkara** [comment]
@PaulDach on the server there is one session storage, it can be redis, or any db. The other applications have keep same session_id then request the session storage application,

There two ways to make, automatic login for different domains. 

The first way;
When you login on any application, send other application the session_id, so all application domain has keep the same session_id.

The second way;
Just make one session application, and one domain. Then request the session application from any other domain on **client-side**, The session application keeps session_id for itself. So, when you request on **client-side**, the application reads session_id from cookie.

So, server-side and client-side requests are different, Client-side request can read cookies on the domain.

I hope I described it clearly.
