### ISSUE TITLE
'POST', 'PUT' pending

### ISSUE THREAD

**Issue by dingchaoyan1983** [nodejitsu/node-http-proxy#1304]
```
var express = require('express');
var httpProxy = require('http-proxy');

var proxy = httpProxy.createProxyServer({
  target: 'http://localhost:5984',
  changeOrigin: true,
});

var router = express.Router();

/* GET home page. */
router.all('*', function(req, res, next) {
  proxy.web(req, res);
});

module.exports = router;
```
I have above code and app.use('couchdb', routes)

the POST and PUT method will pending, how to resolve it?

**Comment by dingchaoyan1983** [comment]
![image](https://user-images.githubusercontent.com/7593506/47797396-370d8800-dd61-11e8-8189-f998273dd7c2.png)

**Comment by dingchaoyan1983** [comment]
there is the error

**Comment by ThibautBellamy** [comment]
Hello, 
Verify if you have this in your code : 
app.use(bodyParser.json());
And comment it  !

**Comment by whatl3y** [comment]
@ThibautBellamy this worked for me, that was driving me crazy for an hour or two, thanks for finding the problem and posting it!
