### ISSUE TITLE
test coverage for error paths

### ISSUE THREAD

**Issue by dominictarr** [nodejitsu/node-http-proxy#146]
currently, there are tests for requests that should be proxied correctly, 
but I do not see any tests that check that errors are handled correctly.

  * socket hangup (server proxied to dies part way)
  * econn refused  (there is no server at host:port proxied to)
  * sockets closing part while proxy is writing (can make req.write throw)

those are the errors that I can think of off the top of my head, can anyone else think of any more?

**Comment by jcrugzz** [comment]
Closing due to old age and relevance.
