### ISSUE TITLE
follow-redirects@1.12.0 requires a peer of debug

### ISSUE THREAD

**Issue by mikeharder** [nodejitsu/node-http-proxy#1460]
Installing the latest version of `http-proxy` causes the following warning:

```
$ npm install http-proxy
npm WARN follow-redirects@1.12.0 requires a peer of debug@^3.0.0 || ^4.0.0
but none is installed. You must install peer dependencies yourself.
```

`follow-redirects@1.12.0` moved `debug` from a `dependency` to a `peerDependency`:

https://github.com/follow-redirects/follow-redirects/commit/7b3de648c6604273a55b2b3e57b9c101b2c2e8b5

Related: https://github.com/follow-redirects/follow-redirects/issues/135

**Comment by RubenVerborgh** [comment]
Solved on the `follow-redirects` side by removing the peer dependency. The upcoming `v1.12.1` takes care of things.
