### ISSUE TITLE
need funding for drones

### ISSUE THREAD

**Issue by 4696047344** [nodejitsu/node-http-proxy#1493]
**What’s missing?**

clone drones

**Why?**

funds
And pilots 

**Alternatives you tried**

__Originally posted by @4696047344 in https://github.com/octokit/core.js/issues/272__

**Comment by 4696047344** [comment]
- [ hope for help
]

**Comment by 4696047344** [comment]
> - [ hope for help
> ]

**Comment by NinoSkopac** [comment]
spam
