### ISSUE TITLE
[question] websocket: is it possible to listen on single port and forward to multiple target

### ISSUE THREAD

**Issue by link89** [nodejitsu/node-http-proxy#1534]
Hi, I have a requirement to listen on a single port and forward the request to multiple target, based on different http endpoint. 
An example may look like this

```
ws://localhost:8000/conn1 <=> ws://localhost:9001/cdp
ws://localhost:8000/conn2 <=> ws://localhost:9002/cdp
ws://localhost:8000/conn3 <=> ws://localhost:9003/cdp
```

It would be appreciated if someone can shed me some light on how to do this with `node-http-proxy`.

**Comment by Louis-Tian** [comment]
@link89 was just looking the same things
yes, it works. 

see
https://github.com/http-party/node-http-proxy/issues/533
https://stackoverflow.com/questions/46272908/proxying-websockets-with-single-proxyserver-to-multiple-targets
