### ISSUE TITLE
How to rewrite path of websocket proxy

### ISSUE THREAD

**Issue by link89** [nodejitsu/node-http-proxy#1556]
I am writing a server that can be access via this url:
`ws://localhost:4444/wd/hub/session/58d9870501f9425f0e9fac4da30abf65/se/cdp`
And I want to create a proxy to the actual backend:
`ws://localhost:56249/devtools/browser/f6366785-cf85-4763-8281-2e95f05379cf`

Here is my sample code
```typescript
const app = new Koa();
const server = app.listen(4444, '127.0.0.1');

server.on('upgrade',  (req, socket, header) => {
    const proxy = createProxyServer({
      forward: `ws://localhost:56249/devtools/browser/f6366785-cf85-4763-8281-2e95f05379cf`
    })
    proxy.ws(req, socket, header);
});
```

But it turns out with the error: `TypeError: Cannot read property 'protocol' of undefined`
I have no idea where I was doing wrong.

**Comment by taewookim** [comment]
`
const proxy = new httpProxy.createProxyServer({
      changeOrigin: true,
      target: 'ws://localhost:56249/blahblah'
  });
`

**Comment by link89** [comment]
You are right, it works with target instead of forward.
