### ISSUE TITLE
Is there a way to stop proxy based on request?

### ISSUE THREAD

**Issue by otakustay** [nodejitsu/node-http-proxy#1568]
We are trying to make a "mock by proxy" middleware, which is to proxy a request and cache its response, for the second time an identical request is landed, we respond it immediately with the cached response and not to proxy it.

When `proxyRes` is fired, the request has already been proxied to target server, and it seems we are unable to configure `proxyReq` to stop proxy.

**Comment by DannyFeliz** [comment]
@otakustay did you find a way to handle this?

**Comment by avin** [comment]
@DannyFeliz it stops request:
```
proxyReq.emit('close');
```

Example:
```
proxy.on('proxyReq', (proxyReq, req, res, options) => {
  if (req.url.startsWith('/test')) {
    res.end('{"foo": "bar"}');
    proxyReq.emit('close');
  }
});
```
