### ISSUE TITLE
Reverse Proxy Randomly Hangs for Larger Data When Running With Bun Runtime

### ISSUE THREAD

**Issue by joshunrau** [nodejitsu/node-http-proxy#1649]
The issue occurs when using `http-proxy` with Bun. I have created a repo reproducing this (see `http-proxy` branch): https://github.com/joshunrau/bun-vite-bug.

A dummy server listening on port 8000 is configured to send a JSON response with some randomly generated bytes (100KB). A proxy server listening on port 9000 proxies requests to port 8000. 

When run with NodeJS (`node main.js`) everything works as expected. However, when running with Bun (`bun main.js`) the HTTP request occasionally hangs. I have also created an issue for [Bun](https://github.com/oven-sh/bun/issues/5737) and [Vite](https://github.com/vitejs/vite/issues/14413).

https://github.com/oven-sh/bun/issues/5737
https://github.com/vitejs/vite/issues/14413

**Comment by Electroid** [comment]
This is on Bun to fix, please close this issue and track progress on oven-sh/bun#5737
