### ISSUE TITLE
IP of request not being forwarded

### ISSUE THREAD

**Issue by remy** [nodejitsu/node-http-proxy#186]
I'm using node-http-proxy as a hostname only proxy that redirects to local node servers I'm running.

I'm using connect's logger middleware on my servers (not the proxy) and although most of the information is correct, the origin of the request is coming from 127.0.0.1 - which I can assume is actually the IP of the proxy rather than the proxied request.

Any way this can be fixed (or is there some flag I've missed)?

**Comment by klesun** [comment]
A note for future readers: you have to pass [`xfwd: true`](https://github.com/http-party/node-http-proxy/blob/9b96cd725127a024dabebec6c7ea8c807272223d/lib/http-proxy.js#L26-L42) parameter to the `createProxy()`, otherwise there will be no `x-forwarded-for` header in the forwarded request.

```javascript
const proxy = httpProxy.createProxy({xfwd: true});
```
