### ISSUE TITLE
How to set up a Forward Proxy for HTTPS request ?

### ISSUE THREAD

**Issue by penkween** [nodejitsu/node-http-proxy#197]
Hi,

I am trying to use Node.js + http-proxy to function as a transparent Forward Proxy, something like Squid/Tinyproxy. While proxy to HTTP site is ok, but currently facing problem proxy to HTTPS site. Below is what I did try.
# Forward Proxy for HTTP request - OK

httpProxy.createServer(function (req, res, proxy) {      //===> This create a Forward Proxy 
    uri = url.parse(req.url);
    var port = 80;
   proxy.proxyRequest(req, res, {
        host: uri.hostname,
        port: port
    });
}).listen(8000);

The above Forward Proxy can only  proxy to HTTP (not HTTPS) site,  for HTTPS site eg. https://github.com/nodejitsu/node-http-proxy  , this proxy simply fail to load it. 
# Forward Proxy for HTTPS request  -  How ????

var opts = helpers.loadHttps();
httpProxy.createServer(8000, 'localhost', {             //===> This create a Forward Proxy
  https: opts,
  target: {
    https: true
  }
}).listen(8080);

https.createServer(opts, function (req, res) {                     //==>This create a LOCALHOST Target HTTPS server
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.write('hello https\n');
    res.end();
}).listen(8000);

With referring to the sample "proxy-https-to-https.js", the above Forward Proxy only help to proxy all HTTPS request to the LOCALHOST Target HTTPS server which is running at PORT=8000. <b>How do we make this Forward Proxy to proxy to any EXTERNAL Target HTTPS site for example:  https://github.com/nodejitsu/node-http-proxy ?</b>

Anyone, pls help

Thanks .

**Comment by goelayu** [comment]
@penkween Even the simple http proxy forwarding doesn't work with the latest version of the library. 
It keeps giving me ` Must provide a proper URL as target`. This is because there is no `options.target` in the options you have provided to the `createServer` function. 

Any help would be sincerely appreciated
