### ISSUE TITLE
Proxy flash socket policy requests

### ISSUE THREAD

**Issue by robertothais** [nodejitsu/node-http-proxy#224]
Some libraries such as socket.io can fall back Flash based sockets when the client does not support WebSockets. To achieve this, the client's Flash program first needs to request a 'socket policy file' from the server. This request consists of a self-closing XML node followed by the null byte sent over raw TCP:

```
<policy-file-request/>\0
```

node-http-proxy will drop this request, causing the Flash socket connection to fail.

**Comment by dvideby0** [comment]
@konklone I followed your instructions for policyfile but I get an error that the address is in use. I have been going in circles with this for a bit. Any help would be greatly appreaciated

```javascript
var express = require('express');
var app = express();
var server = require('http').createServer(app).listen(process.env.PORT || 9009);
app.use(express.static(__dirname + '/public'));
var pf = require('policyfile').createServer().listen(null, server);
var io = require('socket.io')({
  transports: ['websocket']
}).listen(server);
```

**Comment by konklone** [comment]
@dvideby0 It sounds like you might already have an instance of the server running in some other terminal?

**Comment by dvideby0** [comment]
Unfortunately no and the code I put above fails all on its own (without any other logic). Not sure if there is something additional I am supposed to add but I should probably point this issue to the author. Thank you for the help sir!
