### ISSUE TITLE
Support for HTTP CONNECT?

### ISSUE THREAD

**Issue by tonygambone** [nodejitsu/node-http-proxy#230]
Does node-http-proxy support HTTP CONNECT requests, like:

```
CONNECT example.com:443 HTTP/1.1
Host: example.com:443
```

The proxy would then maintain the two connections, and forward the SSL traffic between the client and the target server.

If so, how do I set this up?

Thanks

**Comment by regevbr** [comment]
Working gist - https://gist.github.com/regevbr/de3f5e0475aedd9081608663241bee10

**Comment by imhazige** [comment]
Inspired by these discussion, I have create a working project. https://github.com/imhazige/node-http-connect-proxy

**Comment by hktalent** [comment]
@coderarity  @tonygambone @regevbr  @imhazige 
socks4 or socks5 througth  http proxy use
``
CONNECT % HTTP/1.1
Host: %
```

**Comment by hktalent** [comment]
@coderarity @tonygambone @regevbr @imhazige
```
node node-http-proxy -x "http://127.0.0.1:883" -u http://ip.cn
node node-http-proxy -x "socks4://127.0.0.1:883" -u http://ip.cn
```

**Comment by shirshak55** [comment]
I recommend using proxy-chain for such task.
