### ISSUE TITLE
It should be easy to set up a forward proxy

### ISSUE THREAD

**Issue by ddopson** [nodejitsu/node-http-proxy#301]
node-http-proxy is great for reverse proxies.  It's also wildly intimidating at first glance.

Sometimes you just want a simple vanilla forward-proxy.  Also, forward proxying is conceptually simpler to explain.  Thus here's two suggestions:

1)  Start the documentation with a forward proxy example ... it's a clean way of explaining the core proxy loop.

eg, 

```
var server = HttpProxy.createServer(function (req, res, proxy) {
  url = Url.parse(req.url);
  host = url.host;
  port = url.port || 80;
  console.log("Proxying #{host}:#{port}");
  proxy.proxyRequest(req, res, {
    port: port,
    host: host,
    https: true
  });
}
```

And perhaps a quick "terms definition" would be helpful. forward_proxy=xxx, reverse_proxy=yyyy

2) How on earth do you proxy an HTTPS request?????

I got as far as this:

```
module.exports = HttpProxy.createServer {
  https: {
    key: fs.readFileSync('server.key'),
    cert: fs.readFileSync('server.crt')
  }   
}, (req, res, proxy) ->
  url = Url.parse(req.url)
  port = url.port || 443 
  console.log "Proxying #{url.host}:#{port}"
  proxy.proxyRequest(req, res, {
    port: port
    host: url.host
    https: true
  })
```

But it didn't work.  I get "Proxy CONNECT aborted" when I do "curl https://foo.bar.baz" --proxy1.0 localhost:7878

**Comment by grit96** [comment]
@indexzero that link is broken, is there a solution to this problem?

**Comment by ShayBox** [comment]
I want to do this too, but I can't figure it out

**Comment by grit96** [comment]
I ended up using a more fully featured HTTP proxy https://github.com/alibaba/anyproxy

**Comment by ShayBox** [comment]
Thank you ^.^ I've been trying to figure this out for 3 days
