### ISSUE TITLE
Simple HTTP->HTTPS Proxy Example?

### ISSUE THREAD

**Issue by cweichen** [nodejitsu/node-http-proxy#304]
Hi,

I'm a node/node-http-proxy novice, and I'd like to use node-http-proxy to create an HTTP->HTTPS proxy server. I.e. a client would connect to the proxy over HTTP, and on the back-end it would talk to an HTTPS target web server. The two examples given are for HTTPS->HTTP and HTTPS->HTTPS, but not HTTP->HTTPS.

Maybe it's obvious from these examples how to do it, but I'm not able to figure it out.

Here's a sample of my code:

```
var httpProxy = require('http-proxy');

httpProxy.createServer(function (req, res, proxy) {
  proxy.proxyRequest(req, res, {
    host: 'secure.target.host',
    port: 443,
    https: true
  });
}).listen(8000);
```

When I try to connect to http://localhost:8000 I get a 500 Internal Server Error with the body

```
An error has occurred: {"code":"ECONNRESET"}
```

If anyone can show me what I'm doing wrong, that would be greatly appreciated! Thanks!

**Comment by patoi** [comment]
https://github.com/nodejitsu/node-http-proxy/blob/master/examples/http/proxy-http-to-https.js

**Comment by ericmdantas** [comment]
In case someone's having problem with it, I've created a simple working repo: https://github.com/ericmdantas/simple-node-https-proxy

**Comment by Valeriu92** [comment]
@ericmdantas I'm trying to use your repo to access secured web pages, but it seems to not be working because I get Secure Connection Failed in the web page...

**Comment by ericmdantas** [comment]
@Valeriu92, when I access `https://localhost:9998/api/server2` I get the payload correctly: `{"msg2":"came from server2"}`

**Comment by suculent** [comment]
It works for me only with secure: false in options which is unfortunate, becauase the target server has valid letsencrypt certificate. How do I debug the SSL layer verbosely to see why is the 'first certificate' invalid?

**Comment by rickysahu** [comment]
I had to use these options
```
{
  secure: false,
  target: 'https://localhost:443',
}
```
