### ISSUE TITLE
slow performance using basic-proxy.js vs. no proxy

### ISSUE THREAD

**Issue by robertlmullen74** [nodejitsu/node-http-proxy#305]
Hey all,
I have been running some ab tests against the basicproxy.js service and have noticed it's about 3 times slower using the proxy than not.  I'm on node 0.8.8 and ubuntu 11.10.

Using proxy
>ab -c 10 -n 1000 http://127.0.0.1:8000/   
Total response time was approx. 4 seconds 

No proxy
>ab -c 10 -n 1000 http://127.0.0.1:9000/
Total response time was approx. 1.7 seconds 

I ran the proxy with node http debugging enabled for a single request and this was the output.
NODE_DEBUG=http node basic-proxy.js

1 request through proxy
HTTP: SERVER new http connection
HTTP: server response shouldKeepAlive: false
I'm proxyrequest
get base result
HTTP: outgoing message end.
HTTP: SERVER new http connection
HTTP: server response shouldKeepAlive: true
HTTP: write ret = true
HTTP: outgoing message end.
HTTP: AGENT incoming response!
HTTP: AGENT isHeadResponse false
HTTP: write ret = true
HTTP: AGENT socket keep-alive
HTTP: outgoing message end.
HTTP: server socket close
HTTP: server socket close

1 request without proxy
HTTP: SERVER new http connection
HTTP: server response shouldKeepAlive: false
HTTP: write ret = true
HTTP: outgoing message end.
HTTP: server socket close

Is the performance difference simply because we're asking the proxy to do that much more, that 3x increase seems like something is askew here.  I tested this with different ab parameters, played around with the maxSockets settting and tried a different http agent, but nothing seemed to speed up going through the proxy.    I'm surprised at the discrepancy here, am I missing something?  

Thanks,
Rob

**Comment by jcrugzz** [comment]
It would be good to have benchmarks related to the newest version of `http-proxy` on node `4.x.x` and forward. Open a new issue if there are any issues here but there will inevitably be some overhead.
