### ISSUE TITLE
Reverse Proxy port rewriting for HTTP3xx Location headers

### ISSUE THREAD

**Issue by jayv** [nodejitsu/node-http-proxy#318]
When receiving HTTP3xx server side redirects, the Location header is not entirely rewritten by the proxy, except for rewriting http to https, but in fact servername and port should be translated as well if they match the backend server and port, to make the process transparent to the browser. 

So if the Location header contains http://backendhostname:backendport/foo/bar it should be rewritten to http://proxyhost:proxyport/foo/bar while still applying the http to https conversion as currently implemented.

**Comment by jcrugzz** [comment]
This should be solved in the latest http-proxy. Please open a new issue if you see a problem
