### ISSUE TITLE
`Cannot GET //socket.io/socket.io.js` when using Express, Socket.io and node-http-proxy

### ISSUE THREAD

**Issue by mrryanjohnston** [nodejitsu/node-http-proxy#352]
The following gist produces a `socket.io/socket.io.js 404 (Not Found)` error on the browser's side:
https://gist.github.com/4324446

This gist does not reproduce that error: 
https://gist.github.com/4324576

**Comment by jcrugzz** [comment]
Closing due to old age and related to old version of `http-proxy`
