### ISSUE TITLE
Doesn't work as middleware if next() is called after a timeout

### ISSUE THREAD

**Issue by ghost** [nodejitsu/node-http-proxy#354]
I'm able to use the proxy just fine if previous middleware calls next() syncronously. But if I put it in a db callback, or just a simple setTimeout(), it stalls and never responds. I've confirmed that it's entering the middleware function made with httpProxy.createServer, but the proxy.proxyRequest doesn't ever come back. Any ideas?

**Comment by jcrugzz** [comment]
Closing due to old age and relation to old version of `http-proxy`
