### ISSUE TITLE
Server-sent events not supported?

### ISSUE THREAD

**Issue by cauburtin** [nodejitsu/node-http-proxy#357]
the following code http://pastie.org/private/esae5stq8jxw1lioo8vclq
works if you gave 2 browsers on 127.0.0.1:8000/notify 
and execute 

    source = new EventSource('/events');
    source.onmessage = function(e) {
    	console.log(e.data);
    };

in the console of one, then refresh the other

but on 127.0.0.1/notify the proxying blocks server sent events

**Comment by afterthought** [comment]
This is an issue for us too!!!!!

**Comment by jcrugzz** [comment]
If this is still a problem for people, open a new issue. This seems like a candidate for a separate module

**Comment by davej** [comment]
This is an issue for me. It works for a period of time and then I get an error in the browser console: "net::ERR_INCOMPLETE_CHUNKED_ENCODING"… then it stops working.

Works perfectly if I load the site directly (i.e. not through the proxy).

Code I'm using to proxy request/responses is:
```
proxy.web(req, res, { target = 'http://localhost:8888' })
```
