### ISSUE TITLE
Recognize 303, 307 and 308 and do not crash on malformed responses

### ISSUE THREAD

**Issue by Rob--W** [nodejitsu/node-http-proxy#361]
This part of the code needs to be changed: https://github.com/nodejitsu/node-http-proxy/blob/v0.8.7/lib/node-http-proxy/http-proxy.js#L250-L257

to

```javascript
    var statusCode = response.statusCode;
    if (statusCode === 301 || statusCode === 302 || statusCode === 303 || statusCode === 307 || statusCode === 308) {
      if (self.source.https && !self.target.https) {
        response.headers.location = (response.headers.location || '').replace(/^http:/, 'https:');
      }
      if (self.target.https && !self.source.https) {
        response.headers.location = (response.headers.location || '').replace(/^https:/, 'http:');
      }
    }
```

The changes are:

1. Status code 303, 307 and 308 are recognized and correctly rewritten.
2. When some stupid server does not include the Location header with the status, the server will still stay alive (opposed to crashing with message "Cannot call method 'replace' of undefined")

(and a minor change: Removed the backslash before the colon in the RegExp)

**Comment by jcrugzz** [comment]
This is related to an older version of http-proxy. Closing.
