### ISSUE TITLE
test-http-many-keep-alive-connections is failed

### ISSUE THREAD

**Issue by abarre** [nodejitsu/node-http-proxy#367]
Currently, the test test-http-many-keep-alive-connections is failed but the build is considered as fine by travis. Is it normal?

So, should we pass the build as failed if a test in the core section fails?
Actually, I don't understand the interest of the tests of the core folder since they seem to test Node http module itself rather than the http-proxy module.

**Comment by jcrugzz** [comment]
This is no longer relevant with the current version of `http-proxy`
