### ISSUE TITLE
How to do 301 Redirects

### ISSUE THREAD

**Issue by emotely** [nodejitsu/node-http-proxy#37]
I'm trying to remove the www. requests to point them to the canonical non www. urls. This is the make sure copy pasted urls point to one domain and thus not divide up my Google Page Rank juice across the two domains.

**Comment by jcrugzz** [comment]
This should technically be supported with https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-outgoing.js#L49-L70. If not please open a new issue.

**Comment by SukantGujar** [comment]
How about support for `autoProtocolRewrite`, as the option `protocolRewrite` doesn't look at the request protocol to rewrite `location` returned from the target proxy. So if if I want to support both https and http on my entry site, the only option right now is to write a custom `proxyRes` handler.
