### ISSUE TITLE
How to modify the response HTML data going back to the user?

### ISSUE THREAD

**Issue by PhilAndrew** [nodejitsu/node-http-proxy#382]
Hi, I really need to know how to get the response HTML as a string and modify it.

This question has been asked before at stackoverflow but I don't see how to do it.

http://stackoverflow.com/questions/13596942/using-node-js-to-proxy-http-and-modify-response 

In general, I need to get access to all request data and all response data and change the response data in some cases. Thanks!

**Comment by Skyross** [comment]
How about using [replacestream](https://www.npmjs.com/package/replacestream)?

**Comment by akshayl** [comment]
Harmon / Trumpet allow you to replace a html element, but what if you want to insert elements at various points in the document being returned?

**Comment by No9** [comment]
Hi @akshayl  
https://github.com/No9/harmon/blob/master/examples/rotate.js 
Demonstrates adding an additional style tag in the head without replacing. 

Does this fit your use case?

**Comment by akshayl** [comment]
Thanks for your reply @No9 
That example seems to replace the entire head tag including the script tag which outputs the message "The piece of javascript also inside the head tag wasn't touched :)"

Before:
`<html><head><script>window.onload = function () {document.getElementById("message").innerHTML = "The piece of javascript also inside the head tag wasn't touched :)";}</script></head><body><h3>A simple example of injecting some css to rotate an image into a page before it is rendered.</h3><image src="http://i.imgur.com/fpMGL.png" /><div id="message"></div></body></html>`

After:
`<html><head><style type="text/css"> img { -webkit-transform: rotate(-90deg); -moz-transform: rotate(-90deg); filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);}</style></head><body><h3>A simple example of injecting some css to rotate an image into a page before it is rendered.</h3><image src="http://i.imgur.com/fpMGL.png" /><div id="message"></div></body></html>`

**Comment by No9** [comment]
@akshayl ah now I get you. 
So https://github.com/No9/harmon/blob/master/examples/doge.js#L22 
Shows how you can hold the content of the node and then use it afterwards. 
The sample just logs it to console but I think this might be what you are looking for?

**Comment by shlomihassan** [comment]
hi guys i am working with the same solution 

//
// Create a proxy server with custom application logic
//
httpProxy.createServer(function (req, res, proxy) {
  //
  // Listen to the `proxyResponse` event. Make note that 
  // the first two arguments to this handler are the `req`
  // and `res` in the existing scope and I'm indicating that 
  // they are meaningless by assigning them the var name `_` 
  //
  req.on('proxyResponse', function (_, _, proxyRes) {
    proxyRes.on('data', function (chunk) {
      //
      // This is the data from the target server, but modifying
      // it will not affect the outgoing `res`. 
      // 
    });
  });

  //
  // Put other custom server logic here
  //

  // Now make the proxy request.
  proxy.proxyRequest(req, res, {
    host: 'localhost',
    port: 9000
  });
}).listen(8000);

but in sum cases i am getting only half of the data 
is there a way to get all the data no mater the size?

shlomi

**Comment by tarkeshwars** [comment]
Hey @shlomihassan! Were you able to solve the issue with getting half the data for larger files?

**Comment by ndarilek** [comment]
Sorry to hijack this issue, but I want to do exactly what this issue says I *should* be able to. I want to inject an httpProxy between clients and a JSON API server, *only* observe the JSON data before passing it back, and perform server-side logic. This seems like it should be easy but it isn't. Here is my code:

```
proxy.on("proxyRes", (proxyReq, req, res) => {
  res.on("data", (msg) => {
    console.log("msg", msg)
  })
  res.on("end", () => {
    console.log("end")
  })
  res.on("finish", (data) => {
    console.log("finish", data)
  })
})
```

I just get a bunch of `finish` events and no data. Using this issue because it was what I found when I searched, and I'd have expected the code above to work but either I'm putting it in the wrong place or this solution is outdated.

I'm stuck on Node 0.10.43 if that makes a difference--not my choice, unfortunately.

**Comment by ndarilek** [comment]
And of course 5 minutes after I post that issue, I spot my typo:

```
proxy.on("proxyRes", (proxyRes, req, res) => {
```

I.e. The first parameter to the event callback is a `res`, not a `req`. Sorry for the spam folks. The lesson for the day is coffee first, then code.

**Comment by tommybananas** [comment]
For the record I don't think [replaceStream](https://www.npmjs.com/package/replacestream) is currently compatible, at least not piping directly from the request object.

**Comment by Armalon** [comment]
I had same problem and only solution I've found I peeped in the very same harmon module: https://github.com/No9/harmon/blob/master/examples/gzipped.js#L47-L64
When the author creates an server which listens 9000 port he uses such a hack when he gzipes the response. He uses zlib.Gzip which is a Transform stream and forwards his regular data through it to gzip it.
So we could do the same, here is the example:

`var http = require('http'),
    connect = require('connect'),
    httpProxy = require('http-proxy');
var replaceStream = require('replacestream');
var app = connect();

var proxy = httpProxy.createProxyServer({});

app.use(function(req, res) {
    // PUT here any Transform stream you wish
    var replace = replaceStream('script', 'NOSCRIPT');
    var _write = res.write;
    var _end = res.end;

    replace.on('data', function(buf){
        _write.call(res, buf);
    });
    replace.on('end', function(){
        _end.call(res);
    });

    res.write = function(data){
        replace.write(data);
    };
    res.end = function(){
        replace.end();
    };

    proxy.web(req, res, { target: 'http://' + req.headers.host });
});

var proxyServer = http.createServer(app);
console.log("listening on port 5050")
proxyServer.listen(5050);`

**Comment by albanm** [comment]
I needed to apply some throttling to node-http-proxy, so not really a transformation of the body but still the best implementation that I could think of is to use a throttle stream (for example [node-stream-throttle](https://github.com/tjgq/node-stream-throttle)). As I didn't want a hackish solution, I made a small addition to the options in this fork: https://github.com/koumoul-dev/node-http-proxy/commit/4db8736ed6d28018d5cb2f541370e6de0972d534

The resTransformStream and reqTransformStream options are exactly what their names suggest: optional transform streams that can be piped between req to proxyReq and proxyRes to res.

If some people are interested and the maintainers are ok with the idea I am willing to work on a proper PR, with doc, test, etc.

**Comment by yorch** [comment]
Found this package: [resp-modifier](https://github.com/shakyShane/resp-modifier) that works fairly well for this usecase

**Comment by trusktr** [comment]
Is there still no easy built-in way to send a different response with http-proxy?

Use case: the proxy may only know when to replace a response with a 302 redirect based on looking at the content, but with the `proxyRes` event it is already too late to replace the response.

**Comment by StanDarius24** [comment]
Hi @trusktr did you find a solution for this particular case?
I also want to modify the body when I receive a certain response code

Thanks!
