### ISSUE TITLE
When providing a full path for proxying, the path is lost.

### ISSUE THREAD

**Issue by viridisdev** [nodejitsu/node-http-proxy#386]
When using a proxy table, like below:

```javascript
var proxyOptions = {
  pathnameOnly: true,
  router: {
    '/accounts/login': 'localhost:8001',
    '': 'localhost:8000'
  }
};
```

All requests to the root of the proxy server (localhost:3000) reach the destination, including the full path. IE: A GET request to localhost:3000/scripts/main.js reaches localhost:8000/scripts/main.js with the path in tact. However, any request to localhost:3000/accounts/login, reaches the destination without the full path. IE a POST request to localhost:3000/accounts/login reaches the destination as a POST to localhost:8001, no path is included. This same behavior persists if the destination includes the full path.

My proxy server script, in total:

```javascript
var httpProxy = require('http-proxy');


 
var proxyOptions = {
  pathnameOnly: true,
  router: {
    '/accounts/login': 'localhost:8001',
    '': 'localhost:8000'
  }
};

 
httpProxy.createServer(proxyOptions).listen(3000);
```

**Comment by jcrugzz** [comment]
Yes this should be provided through a separate module. Would love to see it created!
