### ISSUE TITLE
How pathnameOnly proxy work with href from a text/html response?

### ISSUE THREAD

**Issue by sequoiar** [nodejitsu/node-http-proxy#391]
for example, pathnameOnly proxy routing table is below

'/bar' -> 127.0.0.1:81
'foo' -> 127.0.0.1:82

if GET /bar, response a html with href '/img.jpeg', 
then, user request to GET /img.jpeg, that should be wrong.
the right GET request should be GET /bar/img.jpeg

Any ideas on this issue?

**Comment by jcrugzz** [comment]
This is referenced to the older version of `http-proxy`
