### ISSUE TITLE
hostname router proxy throw "Can't render headers after they are sent to the client"

### ISSUE THREAD

**Issue by bfx81** [nodejitsu/node-http-proxy#405]
http-proxy@0.10.1 (even with 0.10.0) nodejs@0.10.4 (even with 0.10.3)
Ubuntu 12.10 64bit
```
"use strict";
var httpProxy = require('http-proxy'),
    http = require('http');

var options = {
  hostnameOnly : true,
  router : {
    'local.test.it' : '127.0.0.1:9000',
    'api.test.it' : '127.0.0.1:8080'
  }
}
var server = httpProxy.createServer(options);
server.listen(80);
```
```
http.js:734
    throw new Error('Can\'t render headers after they are sent to the client.'
          ^
Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:734:11)
    at ServerResponse.writeHead (http.js:1098:20)
    at ClientRequest.proxyError (/home/bluefox/Projects/dev-biz/gustaff/web/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:203:9)
    at ClientRequest.g (events.js:175:14)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketOnData (http.js:1528:9)
    at TCP.onread (net.js:510:27)
```
There's a tomcat server on localhost:8080 and a nodejs "grunt server" on localhost:9000.
The exception is thrown VERY frequently (it's a 99% ALWAYS) after involving authentication on the tomcat server.
The autentication is obtained with a quite standard session cookie with the following workflow:
* api.test.it/auth/login --> redirect to an OAuth provider
* OAuth provider --> redirect to api.test.it/auth/result (this page validate the user and return a session)

The app itself on tomcat allow CORS calls exchange.
Any idea? Tnx in advance

**Comment by LoganBarnett** [comment]
Ran into this situation where I was bouncing back the Origin header as Access-Control-Allow-Origin to address CORS behavior. There's some circumstances where the Origin header isn't set and it was causing undefined to be passed as the header value, causing this error. Making sure we at least passed an empty string worked around this issue.

**Comment by jcrugzz** [comment]
This is an old issue that is no longer relevant to the current version of `http-proxy`
