### ISSUE TITLE
about proxy to 'CONNECT' method

### ISSUE THREAD

**Issue by sequoiar** [nodejitsu/node-http-proxy#408]
How about proxy to 'CONNECT' request?

In case chrome browser:

1. chrome send SPDY 'CONNECT' request first
2. then http-proxy create a tcp/ssl connection to origin server
3. then chrome send 'HTTP CONNECT' request
4. then chrome  fetch HTTPS request over proxy tunnel. 

this way can implements a end-to-end secure forward proxy.

**Comment by steelbrain** [comment]
Bump

**Comment by jcrugzz** [comment]
if you want to tunnel the proxy request through a tunnel (which uses connect), you want to use something like [`tunnel-agent`](https://github.com/mikeal/tunnel-agent) and pass it in as the agent. If there is another use case please be more clear and give a code example that does not work.

**Comment by steelbrain** [comment]
@jcrugzz I am unable to get https to work in `node-http-proxy`, here's the code example https://gist.github.com/steelbrain/b24f795fe92ec229ddb9#comment-1489331

**Comment by jcrugzz** [comment]
Closing old issue. Please open a new issue if this is a problem as there should be better docs around this
