### ISSUE TITLE
Https to https proxy with routing table and self signed certificate does not work in node v0.10.x

### ISSUE THREAD

**Issue by jclevy** [nodejitsu/node-http-proxy#409]
I had a simple proxy working in node v0.8.x (written in Coffeescript):

    Fs = require 'fs'
    HttpProxy = require 'http-proxy'

    HttpProxy.createServer
        https:
            key: Fs.readFileSync './key.pem'
            cert: Fs.readFileSync './cert.pem'
        target:
            https:yes
        hostnameOnly: true
        router:
            'test1.domain.org': '127.0.0.1:8080'
            'test2.domain.org': '127.0.0.1:8081'
    .listen(8000)

When I moved to node v0.10.x every request returned:

    DEPTH_ZERO_SELF_SIGNED_CERT error

I did not find a way to configure my proxy to make it work.

I had to change **http-proxy/lib/node-http-proxy.js**

and insert : **options.rejectUnauthorized = false;**

    exports._getAgent = function _getAgent (options) {
        ...
        options.maxSockets = options.maxSockets || maxSockets;
        options.rejectUnauthorized = false;
        agent = new Agent(options);
        ...

**Comment by jcrugzz** [comment]
New `http-proxy` uses a separate module for routing [`http-proxy-rules`](https://github.com/donasaur/http-proxy-rules)
