### ISSUE TITLE
Is there a way to add/remove server entries dynamically to http-proxy ?

### ISSUE THREAD

**Issue by chiragsanghvi** [nodejitsu/node-http-proxy#413]
Used and played around with http-proxy,good for use.

We've a requirement in our project, where we need to scale/add node servers depending on load/traffic.Is there a way to add an entry to list of servers in http-proxy dynamically ?

**Comment by jcrugzz** [comment]
This is referencing an old version of `http-proxy` but if you come across this issue we have a new module that handles routing and this sounds like a feature that could be requested if needed. [`http-proxy-rules`](https://github.com/donasaur/http-proxy-rules)
