### ISSUE TITLE
(node-http-proxy) Proxy within a http server vs Standalone proxy server

### ISSUE THREAD

**Issue by mpl0916** [nodejitsu/node-http-proxy#422]
Could anyone explain the differences (performance, etc) between plug-in a RoutingProxy instance into a http server and simply a standalone proxy server. Here are links as reference:

https://github.com/nodejitsu/node-http-proxy#proxy-requests-within-another-http-server

vs.

https://github.com/nodejitsu/node-http-proxy#setup-a-stand-alone-proxy-server-with-custom-server-logic

I need a proxy to add additional headers to incoming requests before sending them to a 3rd party API server.

**Comment by jcrugzz** [comment]
Closing old issue, we have a new version of `http-proxy` please open a new issue if you have any issues with it
