### ISSUE TITLE
support timeout event

### ISSUE THREAD

**Issue by sanggyun** [nodejitsu/node-http-proxy#425]
I want to catch event when reverseProxy is on timeout 

maybe ...
in http-proxy.js

    reverseProxy.once('socket', function (socket) {
      if (self.timeout) {
        socket.setTimeout(self.timeout, function(){
          self.emit('timeout', req, res)
        });
      }
    });

**Comment by jcrugzz** [comment]
This is from the old version of http-proxy, please open up a new issue if you run into an issue with the new version! Thanks.
