### ISSUE TITLE
IE9 socket header missing

### ISSUE THREAD

**Issue by samsonradu** [nodejitsu/node-http-proxy#433]
* [WebSocket] header Sec-Websocket-Origin missing  (IE9 with flashsockets)

After upgrading from 0.8.7 to 0.10. Worked fine before that. * XHR works but is unstable. 

Here is my code. even tried to manually add it:
<pre>
 server.on "upgrade", (req, socket, head) ->
     req.headers["sec-websocket-origin"] = req.headers["origin"]
     for e of req.headers
       console.log e + ": " + req.headers[e]
     console.log "Websocket: #{req.url}", head
     backends.express.proxyWebSocketRequest req, socket, head
</pre>

The header now looks like this: 

connection: Upgrade
host: {website.com}
origin: http://{website.com}
cookie: __utma=232169373.1461931670.1369898552.1371626296.1371629001.25; __utmz=232169373.1369898552.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmb=232169373.16.10.1371629001; __utmc=232169373; __atuvc=3%7C17; session=7e2v8ij15hevksve63jjref7g0
sec-websocket-key1: 24  V   #   3 1 8849 5s0
sec-websocket-key2: f+41> I`08f;$51  5 1  6S  -    sO8
Sec-Websocket-Origin: http://{website.com}

**Comment by jcrugzz** [comment]
This is referring to an old version of http-proxy. Please try versions `1.x.x` and open an issue if you have a problem, Thanks!
