### ISSUE TITLE
[feature request] need transparent "CONNECT"

### ISSUE THREAD

**Issue by mrose17** [nodejitsu/node-http-proxy#441]
i'd like to use nodejitsu.com to host an app that does rendezvous between two processes, cf., the "HTTP-specific protocol" implemented here:

    https://github.com/mrose17/node-rendezvous

the problem is that ithe appt needs to be able to "park" an incoming HTTP connection from one client while waiting for a connection from a second client. 

i believe that the easiest way to implement this is for node-http-proxy to implement connect transparently, e.g., node-http-proxy receives

  CONNECT ... HTTP/1.1
  Host: example.nodejitsu.com

establishes a connection to port 8080 on the application, sends the CONNECT verbatim and then transparently copies octets over the connection until it closes, e.g.,

    socket1.pipe(socket2); socket2.pipe(socket1);

what's your thinking?

thanks!

/mtr

**Comment by jcrugzz** [comment]
This question was relevant to nodejitsu as a service before we shut down. Closing due to irrelevance to the library in question as its possible to tap into the `connect` event. Open a new issue if you have a problem.
