### ISSUE TITLE
HTTPs Forward proxy?

### ISSUE THREAD

**Issue by runk** [nodejitsu/node-http-proxy#453]
Is it possible to use the module in https forward mode? I've tried different examples, though without any luck. It works fine for me in reverse proxy mode.

Basically when I try to do:

```
curl -x localhost:8080 https://github.com
```

the proxy doesn't respond anything.

---

Further, is it possible to intercept data in https proxy mode? Like web debugging proxies do, eg. Charles.

**Comment by gebrits** [comment]
hi @runk. Looked at your code but quick question: do I understand correctly that I need an external proxy server running (as identified by `mitmSocketPath`) ? I hoped this was a self-containing https forward proxy. Any help much appreciated

**Comment by runk** [comment]
@gebrits nope, it's just an option to set a path where internal https server keeps its spocket.
