### ISSUE TITLE
"Error: Can't set headers after they are sent" with caronte

### ISSUE THREAD

**Issue by Rush** [nodejitsu/node-http-proxy#469]
Again, I am trying the simplest use case:

```
var caronte = require('./index.js');
var proxy = caronte.createProxyServer({});
var EventEmitter = require('events').EventEmitter;

require('http').createServer(function(req, res) {
    res.end("TEST");
}).listen(8089)

require('http').createServer(function(req, res) {
  proxy.web(req, res, {
            target: require('url').parse("http://127.0.0.1:8089"),
            ee: new EventEmitter()
  });
}).listen(8081);
```

Testing `ab2 -v 2 -c 1 -n 20 http://127.0.0.1:8081/`

```
> node ./test

http.js:708
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at node-http-proxy/lib/caronte/passes/web-outgoing.js:19:11

```

Thanks for your support!

**Comment by mizuiren** [comment]
I have the same problem, "http-proxy": "^1.16.2"
the code :
/***************************/
app.get(/.*?\.mp3/, proxyer);

function proxyer(req,res,next){
    delete req.headers.host;
    return proxy.web(req, res, {target: 'http://fs.open.kugou.com'});
}
/***************************/
It show me log  "Error: Can't set headers after they are sent..." while I'm playing mp3 music sometimes. 
how to fix it?

More detail on "http://www.mizuiren.com/490.html"
