### ISSUE TITLE
Really simple reverse proxy not working correctly.

### ISSUE THREAD

**Issue by quantizor** [nodejitsu/node-http-proxy#506]
I'm at a loss and have tried practically every example in the README.

All I'm trying to do is proxy requests to localhost:9000 to anotherserver.com:80 and return the result. For some reason, the proxy goes to anotherserver.com:80, but the response clearly has an error message saying it's hitting port 9000 on the target server.  What am I doing wrong?

```
var http = require('http'),
    httpProxy = require('http-proxy');

var handler = function (request, response, proxy) {

  proxy.proxyRequest(request, response, {
    host : 'anotherserver.com',
    port : 80
  });

};

httpProxy.createServer({}, handler).listen(9000);
```

**Comment by jtremback** [comment]
Don't know if this is related, but I am getting

```
Error: Parse Error
    at Socket.socketOnData (http.js:1587:20)
    at TCP.onread (net.js:527:27)
```
when using this with local addresses, but not with external addresses.

**Comment by jcrugzz** [comment]
@jtremback open a new issue with some code and a more descriptive depiction of what you are doing
