### ISSUE TITLE
Correct way to set up HTTPS proxy

### ISSUE THREAD

**Issue by djpimp2010** [nodejitsu/node-http-proxy#596]
I have used your repo for a standard HTTP reverse proxy, and it works brilliantly (except a small issue with status codes), and I have been working on a HTTPS version.

I had to get code form another repo for SNI, and I have that successfully set up.

I can go to https://domain1.com:444 and https://domain2.com:444 and both will show the correct certificates, and the default certificates are set as domain1.com

This works brilliantly, and the correct certificate is always shown for the domain, but I cannot get the HTTPS script to use the new version of your API to proxy a request (proxy.web(req,res, {});)

Here is the server that currently proxies to a single target:

```node
var certs = {
		'domain1.com': getCredentialsContext('domain1')
};

var options = {
			  ssl: {
				SNICallback: function(hostname){
				  //console.log(certs[hostname]);
				  return certs[hostname];
				},
				key: fs.readFileSync('/etc/ssl/certs/default.key'),
				cert: fs.readFileSync('/etc/ssl/certs/default.crt'),
			  },
			  hostnameOnly: true,
			  target: 'https://192.168.0.12:443',
			  secure: false,
			}

var server = httpProxy.createServer(options);

console.log('listening 444');
server.listen(444);

```

As said above, this server works halfway, but can only proxy to a single target, After googling, i have noticed you removed the router: {} options

I have tried setting up like this: (but with ssl settings) https://github.com/nodejitsu/node-http-proxy/issues/594

If I set it up like the example in the above issue, then the server wont even listen for connections, although no errors are thrown.

What would be the correct syntax to change to multiple targets from the code above ?
It looked so easy with the router options, I there any way of me botching some old code back in, to get the router options working again?

If not, is there a way I can pick the internal ip to proxy to, depending on the hostname used to access the proxy ?

Node.js has proved very very powerful, and it looks faster than a dedicated nginx reverse proxy !!

Thanks!

**Comment by lsvx** [comment]
Did you ever have any luck setting this up? I am trying to figure how to do SNI with node-http-proxy as well.

**Comment by jcrugzz** [comment]
@lsvx i believe this issue is around the old API usage. My recommendation here is to create a standard HTTPS server (which uses SNI callback) and create a separate `http-proxy` instance to proxy the requests within the handler.

```js
var https = require('https');
var HttpProxy = require('http-proxy');

// Intantiate a proxy that also changes the origin of the incoming request to the target host
var proxy = new HttpProxy({ changeOrigin: true });

var options = {}; // SSL OPTS AND SUCH with SNI callback

https.createServer(options, function (req, res) {
  proxy.web(req, res, {
    target: 'https://whatever.com'
  });
});
```
 Please create a new issue if this does not work out for you as this issue itself is dated. Thanks!

**Comment by lsvx** [comment]
@jcrugzz,

Thanks for your example! I was able to get SNI working perfectly.

**Comment by lekojson** [comment]
@jcrugzz Minor and clever solution!
