### ISSUE TITLE
Performance degrades when using node-http-proxy to proxy http calls to EC2 instance

### ISSUE THREAD

**Issue by sgerace** [nodejitsu/node-http-proxy#614]
My current setup is as follows: I have a Node.js server that is serving http requests (let's call that the main server) and another Node.js server that is proxying requests to the main server (running node-http-proxy v1.0.3). If the main server and proxy server are both running on my machine, everything works great and I don't see any drop in performance when going through the proxy. However, as soon as the main server is running on an EC2 instance (and the proxy still on my local machine), I see the average response time go from 50-100ms to about 800-3000ms per request when I make requests through the proxy vs. directly calling the main server. I'm kind of at a loss because it seems like as far as EC2 (or the network/internet) is concerned, the actual request leaving my machine and coming back to my machine __should__ be the same in both scenarios, correct? If that is the case, then if feels like the issue is somewhere in node/node-http-proxy. However, then why isn't the performance impacted when the main server is running on my machine? Honestly I'm not even sure about the right way to go about debugging the issue and if anyone can provide some guidance I'd be more than happy to run some more tests to help point people in the right direction.

Also, I saw issues #334, #305, and #491, but I didn't feel like any of those could have the same root cause as the issues I'm seeing; feel free to correct me though if that assumption happens to be wrong.

**Comment by vkadam** [comment]
While doing pipe, when I set keepAlive=true for agent, I got the response in near time as direct call, around 3-5ms extra.

**Comment by zohebsait** [comment]
Is there a resolution to this? I am seeing the same issue.

**Comment by antouhou** [comment]
I've got the same issue, and for me setting up http.agent.maxSockets to 10000 solve the problem. Not sure why, since maxSocket defaults to infinity.

```javascript
var httpsAgent = https.globalAgent;
httpsAgent.maxSockets = 10000;

var proxy = httpProxy.createProxyServer({
  agent: httpsAgent
});
```

**Comment by manueltimita** [comment]
Perhaps this will help those for whom the `keepAlive` / `maxSockets` settings don't make a difference: it may very well be down to DNS lookups. I noticed that even when proxying locally, to a virtual machine, if the target is a hostname rather than IP, the response is 100 to 150 ms slower

**Comment by alexw23** [comment]
:+1: getting this when using a host on /etc/hosts

**Comment by Kulikowski** [comment]
Is there any other fix for this? I am seeing the same issue.

**Comment by indexzero** [comment]
The solution to this issue is to use a custom agent or to up the sockets on the default agent, which by default in many older vesions of node is set very low (5 sockets). If you are running on node@4, however, the default number of sockets is high.
