### ISSUE TITLE
No way to grab POST body before sending request?

### ISSUE THREAD

**Issue by dlabey** [nodejitsu/node-http-proxy#667]
Hi all, I need to generate a signature based on the POST body. If I put the proxy.web on the request end method it simply does not work. Has anyone accomplished reading the POST body?

**Comment by mrblackus** [comment]
@seglo I tried the `buffer` option suggested by @jcrugzz and it works like a charm. Idea is to retrieve the body by consuming the request stream, and to store the buffered result on a stream that we will pass to the `buffer` property when calling `proxy.web()`.

Example here, first with a middleware to retrieve the body (you will recognize part of your code as I work with connect-prism):

```javascript
var app = connect()
  .use(function (req, res, next) {
    var buffer = '';
    req.on('data', function(data) {
      buffer += data;

      // Too much POST data, kill the connection!
      if (buffer.length > 1e6) {
        req.connection.destroy();
      }
    });

    req.on('end', function() {
      req.body = buffer;

      //Here we create a new stream with the buffered body on it
      var bufferStream = new stream.PassThrough();
      bufferStream.end(new Buffer(buffer));
      req.bodyStream = bufferStream;

      next();
    });
```

Then, when calling the proxy, just pass this stream:

```javascript
proxy.web(req, res, {buffer: req.bodyStream});
```

**Comment by acanimal** [comment]
I was in a similar situation where I need to load response. Hope it helps: http://www.acuriousanimal.com/2015/08/31/how-to-read-from-a-writable-stream-httpserverresponse-in-node.html

**Comment by chris-tremblay** [comment]
After some searching, and combining information from several posts, the following works for me:
```
const httpProxy = require('http-proxy')
const proxy = httpProxy.createProxyServer({
  target: {
    protocol: 'https:',
    host: [domain name],
    port: 443
  },
  changeOrigin: true
})

app.use((req, res, next) => {
  if (req.url.search([Regular Expression]) >= 0) {
    return proxy.web(req, res)
  } else {
    ...
  }
})

//Assuming content type of 'application/x-www-form-urlencoded'
proxy.on('proxyReq', function (proxyReq, req, res, options) {
  if (req.body) {
    var bodyData = Object.keys(req.body)
      .map(key => `${encodeURIComponent(key)}=${encodeURIComponent(req.body[key])}`)
      .join('&')

    proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData))
    proxyReq.write(bodyData)
  }
})
```

I hope this helps someone, I spent several hours attempting to resolve POST requests failing.

**Comment by claytongulick** [comment]
It wasn't clear to me from reading this what was actually happening.

To expand on this a bit, what's happening here is that the node request is a stream, it can only be read once, after that the stream data is consumed.

When you use body-parser middleware in express, it will consume the request stream body - if you try to proxy the request after this, there's no body stream to send, so the other end of the proxy receives a POST with a content-length, etc... but waits indefinitely to receive the POST body which never arrives.

If you want to proxy POST/PUT or really any requests that contain a body, you have to do that before any middleware consumes the body. 

Also, be aware that for the same reason, middleware that executes after you proxy a request will be affected the same way, once the request stream is consumed there won't be anything for subsequent middleware to read. That's the reason for things like connect-restreamer.

**Comment by linfanxxxx** [comment]
@claytongulick  Thank you very much！ Really helpful

**Comment by cdll** [comment]
Same issue here. Thanks to @claytongulick that i realize i should cache the request.rawBody data by myself.
