### ISSUE TITLE
toProxy option is broken

### ISSUE THREAD

**Issue by samcday** [nodejitsu/node-http-proxy#703]
In the first place it's somewhat poorly documented, so perhaps I'm just doing it wrong.

Say I do this:

```
  req.url = "http://destination/yay";

  proxy.web(req, res, {
    target: "http://mysquidproxy:3128",
    toProxy: true
  });
```

I should expect squidproxy:3128 to receive a `GET http://destination/yay HTTP/1.1`. Instead, it receives a `GET http:/destination/yay HTTP/1.1` - note the single slash after protocol. It looks like `common.urlJoin` is causing the munging here.

**Comment by callmemagnus** [comment]
I'm using 1.11.2 and trying to make my request hit a cntlm proxy.

I see the requests but the url is like:
```
cntlm[32283]: 127.0.0.1 GET /https://<host>/<path>
```

Not the slash at the beginning of the URL ?

I'm using the `toProxy=true` option, putting the proxy as my target and changing the req.url to contain the host part. 

If I disable it, the url becomes only the `<path>`.

Is this a regression ? Or am I badly miss-using the module ?

**Comment by robertklep** [comment]
@callmemagnus FWIW, I got hit by the same issue, turns out that you need to use `prependPath : false`
