### ISSUE TITLE
Secure Website Problem

### ISSUE THREAD

**Issue by odmarkj** [nodejitsu/node-http-proxy#732]
I am trying to create a simple reverse proxy.

Firefox Browser -> Node Proxy -> Proxy 1 (LimeProxies.com) -> Target
Firefox Browser -> Node Proxy -> Proxy 2 (LImeProxies.com, or some other provider) -> Target
Firefox Browser -> Node Proxy -> Proxy 3 (LImeProxies.com, or some other provider) -> Target

Very straight forward. The problem comes in with requesting a secure website, "https://bing.com" for example as compared to "http://bing.com", which has no problems.

``` js
var server = http.createServer(function(req, res) {
jp.process(req, res); // contains a little logic, and a proxy.web() request.
} );
server.listen(8805);
```

When I request a secure website, jp.process doesn't even fire. Through research, I found that server.on('connect', function(){}); was required. By adding this, I was able to see the request for a secure website "https://bing.com".

``` js
server.on('connect', function(req, socketRequest, bodyhead){
var proxy_server = httpProxy.createProxyServer({
timeout: 5000,
proxyTimeout: 5000,
//forward: 'ws://'+req.jproxy.proxy.ip.toString()+':'+req.jproxy.proxy.port.toString(),
target: 'ws://166.78.5.44:9050',
//forward: 'http://'+req.jproxy.proxy.ip.toString()+':'+req.jproxy.proxy.port.toString(),
//target: { host: '166.78.5.44', port: '9050' },
//target: { host: '50.118.136.137', port: '1212' },
//ws: true, // adds websocket support
//xfwd: true, // adds x-forward headers
//toProxy: true, // explicitly specify if we are proxying to another proxy
//secure: true, // verify SSL certificate
//agent: false, // don't send a user agent,
//agent : https.globalAgent,
});
proxy_server.ws(req, socketRequest, bodyhead);
//proxy_server.web(req, socketRequest, bodyhead);
});
```

I've tried both the ws and web methods, with no luck. It attempts to proxy the request, but it fails for some reason through a timeout without any helpful error message.

I've tried dozens of proxies, even SOCKS proxies for the WS method, but I cannot get the request to process successfully.

If I put something like this in the connect method, it works, but the request obviously comes from the nodejs server instead of a 3rd party proxy.

``` js
var srvUrl = url.parse('https://' + req.url);
var srvSocket = net.connect(srvUrl.port, srvUrl.hostname, function() {
socketRequest.write('HTTP/1.1 200 Connection Established\r\n' +
'Proxy-agent: Node-Proxy\r\n' +
'\r\n');
srvSocket.write(bodyhead);
srvSocket.pipe(socketRequest);
socketRequest.pipe(srvSocket);
}); 
```

I am just trying to create a simple reverse proxy, but have been unable to do so for weeks now. Any help is greatly appreciated. Thanks!

**Comment by pose** [comment]
Hi @odmarkj, I'd a similar issue and I could make it work. I've created a gist with a https capable reverse proxy: https://gist.github.com/pose/397be6f20433a1346004 . Hope that helps!

**Comment by pronskiy** [comment]
Hi @odmarkj,

Were you able to accomplish this eventually?  

@pose your example will work for one proxy, but not in case of a chain as @odmarkj specified.

**Comment by gscoon** [comment]
``
var proxy = {host: "127.0.0.1", port: 4444};

server.on('connect', function(req, clientSocket, head){
	console.log('Connect event');

	var headers = Object.assign({}, req.headers);
	delete headers.host; // dont know if this is necessary

	var options = {
		hostname		: proxy.host,
		port			: proxy.port,
		path			: req.url,
		method		: 'CONNECT',
		headers		: headers
	};

	var newReq = http.request(options);
	newReq.end();

	newReq.on('connect', function(res, socket, head){
		clientSocket.write('HTTP/1.1 200 Connection Established\r\n\r\n');
		socket.pipe(clientSocket);
		clientSocket.pipe(socket);
	})

});
``

**Comment by MaxLiebsch** [comment]
Dear all, 
funnily enough after seven years I pass by  this issue.

Did anybody solved this?

I would greatly appreciate the help with this.

Best 
Max.
