### ISSUE TITLE
Canot call method 'split' of null

### ISSUE THREAD

**Issue by Rush** [nodejitsu/node-http-proxy#747]
After recent upgrade my tests break:
```
Uncaught TypeError: Cannot call method 'split' of null
    at Object.common.urlJoin (/code/http-master/node_modules/http-proxy/lib/http-proxy/common.js:142:23)
    at Object.common.setupOutgoing (/code/http-master/node_modules/http-proxy/lib/http-proxy/common.js:75:26)
    at Array.stream [as 3] (/code/http-master/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:109:14)
    at ProxyServer.<anonymous> (/code/http-master/node_modules/http-proxy/lib/http-proxy/index.js:80:21)
    at Object.ProxyMiddleware.requestHandler (/code/http-master/modules/middleware/proxy.js:9:4607)
```

**Comment by damonmcminn** [comment]
I also experienced this. The problem was a result of rewriting `req.url` to an empty string:

`/path/ => /`
`/path => ''`

So `url.parse('').path => null` which means `common.urlJoin` was being passed `null` as it's last argument.

I have written a fix and submitted a pull request: https://github.com/nodejitsu/node-http-proxy/pull/798

**Comment by efkan** [comment]
Hey @Rush , 

Did this fixing solve your problem?
Despite `common.js` file had fixed I get same error.

Is there any one in my case?

**Comment by damonmcminn** [comment]
@efkan can you give more information?

**Comment by efkan** [comment]
Hi @damonmcminn ,

actually I am a newbie to use `node-http-proxy`. And I've been trying to implement on `localhost`. If I can implement `http` then I have to implement as `https`.
Someone on stackoveflow said that `before proxy operation URL should be resolved by DNS`. But really I don't know.

var fs = require('fs'),
    httpProxy = require('http-proxy'),
    express = require('express'),
    vhost = require('vhost'),
    app = require('./app').service,
    api = require('./api').service;

var options = {
  changeOrigin: true,
  target: {
    'process.localhost': 'http://127.0.0.1:2443',
    'api.localhost' : 'http://127.0.0.1:3443'
  }
}

httpProxy.createServer(options)
.listen(1443, function() {
  console.log('Proxy server is listening on port 1443')
})

app
.use(vhost('process.localhost', app))
.listen(2443, function() {
  console.log('APP server is listening on port 2443')
})

api
.listen(3443, function() {
  console.log('API server is listening on port 3443')
})
