### ISSUE TITLE
Cannot change path in target site?

### ISSUE THREAD

**Issue by yleemj** [nodejitsu/node-http-proxy#758]
If the income request url is http://example.com/abc, and then we call 

    proxy.web(req, res, {target: "http://target.com:8080"})

the request will be proxied to http://target.com:8080/abc, can it be proxied to a different path, e..g  http://target.com:8080/something_else/xxxx, or just http://target.com:8080?
Thanks!

**Comment by ferozed** [comment]
I have the same usecase. I want to run a proxy that forwards to a remote server, but changes the target path:

So for eg:

http://proxy.com/foo -> http://target.com/bar

I have tried ignorePath=true, and prependPath=false and none of them seem to work.

Here are my results:

prependPath: false, ignorePath: true -> http://target.com/foo
prependPath: true, ignorePath: true -> http://target.com/bar/foo
prependPath: true, ignorePath: false -> http://target.com/bar/foo
prependPath: false, ignorePath: false ->  http://target.com/foo

How do I get it to forward to just the target Url I specify:

```
        // You can define here your custom logic to handle the request
        // and then proxy the request.
        proxy.web(req, res, { target: forwardUrl });
```

Essentially, I am trying to write a general purpose forwarding proxy, that will use the path of the incoming request to forward to any number of target applications.

**Comment by mereghost** [comment]
I have the same use case and issue right now. =/

**Comment by pwasem** [comment]
How and when did reassign req.url? Could you post some code snippet please? Thank you!

**Comment by jcrugzz** [comment]
ignorePath is currently an unmerged PR. @ferozed did you use that branch? Let me merge the pull-request and bump the version and see if this fixes the issue you guys are having.

**Comment by jcrugzz** [comment]
please try `1.11.0` with `ignorePath` option. Otherwise open a new issue as this should be fixed.
