### ISSUE TITLE
Can't proxy when calling an synchronous function

### ISSUE THREAD

**Issue by xiaok** [nodejitsu/node-http-proxy#764]
```
proxy.web(request, response, {
		       		target: "http://" +host + ":" +port + ""
		    	});
```
works well but 
```
                       setTimeout(function(){
				proxy.web(request, response, {
		       		target: "http://" +host + ":" +port + ""
		    	});

		    	proxy.on('error', function(err) {
					console.log(e); 
				});
			}, 1000);
```
can't work, and no error log. can someone help me to solve this problem

**Comment by jcrugzz** [comment]
@xiaok can you turn this into a failing test? it should not matter if you are doing anything asynchronous before proxying if you are running on `0.10.x`+.

**Comment by xiaok** [comment]
@jcrugzz very strange, when I removed "server.use(express.limit('5mb'))" , the proxy worked well.

**Comment by jcrugzz** [comment]
@xiaok this is due to the middleware in question buffering the entire stream into memory in order to assess the length. This breaks the proxy as the request stream you are trying to proxy no longer has any data in it.
