### ISSUE TITLE
https proxy problem with node 0.10

### ISSUE THREAD

**Issue by faridz88** [nodejitsu/node-http-proxy#765]
I get the following error when i try to use a simple HTTPS -> HTTP proxy same as sample code in main page
It works fine at first, but the exception gets throw after 5-6 https requests.

>v0.10.33
_stream_readable.js:748
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:748:11)
    at IncomingMessage.Readable.pause (_stream_readable.js:739:3)
    at IncomingMessage.ondata (/home/nodejs/cache/node_modules/http-stale-cache-proxy/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:361:20)
    at IncomingMessage.emit (events.js:95:17)
    at flow (_stream_readable.js:614:9)
    at IncomingMessage.pipeOnReadable (_stream_readable.js:642:5)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)

but there is no problem when node is downgraded to v0.8.28
I think that it may be an incompatibility issue with node v0.10

There is also a [related issue](https://github.com/componentjs/component/issues/364) that may help.

**Comment by jcrugzz** [comment]
@faridz88 are you using version `1.x.x`?

**Comment by faridz88** [comment]
Yes, I am currently using http-proxy@1.8.1
The other error when not using [http-stale-cache-proxy](https://www.npmjs.com/package/http-stale-cache-proxy) as my http webserver:
>/home/nodejs/cache/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at Socket.socketCloseListener (http.js:1527:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:466:12)

My Code:
```javascript
var fProxy = httpProxy.createServer({
  target: {
    host: 'SERVER_IP',
    port: 80
  },
  agent: false,
  ssl: {
    key: fs.readFileSync(__dirname+'/private.key', 'utf8'),
    cert: fs.readFileSync(__dirname+'/public.cert', 'utf8')
  },
}).listen(443);
```

**Comment by kokarn** [comment]
The problem is that you don't handle errors first and foremost.

Here's an example of some REALLY basic error handling
```
// Basic error handling
fProxy.on( 'error', function( error ){
    console.log( error );
});
```
and [here](http://stackoverflow.com/questions/10814481/how-to-debug-a-socket-hang-up-error-in-nodejs) is a good answer on SO about it.

**Comment by jcrugzz** [comment]
@faridz88 your first error was from using  `http-stale-cache-proxy` which uses an old version of `node-http-proxy` that does not work on `0.10.x` properly. The second error is related to the remote server you are proxying to breaking the socket connection. An example of how to handle errors in these cases is [here](https://github.com/jcrugzz/proxy-server/blob/master/index.js#L53-L65)

**Comment by faridz88** [comment]
@jcrugzz You are right. I'l discuss the first error on `http-stale-cache-proxy`'s  page and the second error has been handled properly.
Thanks a lot.

**Comment by faridz88** [comment]
Unfortunately the problem has not been solved yet. And as i see `http-stale-cache-proxy` is using `node-http-proxy "0.10.4"`

P.S I used npm to install `http-stale-cache-proxy` and it installed this version here `./node_modules/http-stale-cache-proxy/node_modules/http-proxy`

**Comment by jcrugzz** [comment]
@faridz88 its using an OLD version of `http-proxy` that does not run on `node 0.10.x` or later. it can only be used on `0.8.x`.

**Comment by jcrugzz** [comment]
So http-stale-cache-proxy would need to upgrade to the newest version if it wants to support node `0.10.x`
