### ISSUE TITLE
Memory Leak (or high memory usage?)

### ISSUE THREAD

**Issue by Mewte** [nodejitsu/node-http-proxy#766]
I've been trying different things for about a week now. I'm using http-proxy to proxy web sockets to socket.io. I've tried several different ways to restructure this, and I'm just completely out of ideas. Is request being loaded into memory when I set a header and not being released when the socket disconnects? My socket.io server never goes above 150MB, yet this code seems to reach around 300-350mb after about 6-8 hours or so. Has anyone else had a similar issue and can offer some sort of advice? I really need a web socket proxy that I can use logic with (and node is perfect..), but if this high memory usage keeps climbing at the rate it does, I'm going to have to scrap this project.

```javascript
var http = require('http');
var httpProxy = require('http-proxy');
var config = require('./config');
console.log(config);
var proxy = new httpProxy.createProxyServer();
proxy.on('error', function(e,req,res){
	res.end();
});
proxy.on('proxyReq', function(proxyReq,req,res,options){
	if (req.headers['custom-header'] == undefined)
		proxyReq.setHeader('custom-header',req.connection.remoteAddress);
});
var proxyServer = http.createServer(function (req, res) {
	proxy.web(req, res, {target: {
							host: config.host,
							port: config.port
	}});
});
proxyServer.on('upgrade', function (req, socket, head) {
	proxy.ws(req, socket, head, {target: {
							host: config.host,
							port: config.port,
							ws: true}});
});
proxyServer.listen(config.listen_on);
```
After reading the docs one more time, I noticed there's a close event for proxies.
Should I be doing something within the close event?
such as:
```javascript
proxy.on('close', function (req, socket, head) {
     req = null;
     head = null;
     socket.end or socket.close or something?
     then socket = null?
});
```
Any help would be greatly appreciated.

**Comment by jcrugzz** [comment]
@Mewte hmm this might be something specific to websocket proxying but this still seems odd. @goldfire have you seen anything like this? @3rd-Eden do you have any ideas? Could socket.io somehow cause a leak on the proxy level? Im very interested to see where the issue lies. Could you also list what node version you are using? I'd recommend the latest `0.10.35`.

**Comment by Mewte** [comment]
@jcrugzz Thanks for the response, after further running for 10 hours, the memory usage has stabilized at around 135-150mb. Previously I was doing 
```javascript
req.headers['custom-header'] = req.connection.remoteAddress
```
inside the proxyServer web request, which I think was causing the memory leak. After moving it to the proxyReq event (as seen above) it seems to be fine. (I must have forgot to git pull on the server I was testing on) Thanks for your help!

**Comment by jcrugzz** [comment]
@Mewte glad to hear it and no problem!

**Comment by Dipeshlohani** [comment]
@Mewte @jcrugzz I am having a similar problem, Did you solve it?
