### ISSUE TITLE
Is there a way to enable keep-alive?

### ISSUE THREAD

**Issue by voronianski** [nodejitsu/node-http-proxy#767]
I'm running several express apps via this proxy. But http://www.webpagetest.org/ test complains about `Keep-Alive not Enabled`. I assume that it's an issue with proxy, is there a way to enable keep-alive?

**Comment by jcrugzz** [comment]
@voronianski use something like [`keep-alive-agent`](https://github.com/ceejbot/keep-alive-agent) or [`agentkeepalive`](https://github.com/node-modules/agentkeepalive) or even the standard `http.Agent`. Just make sure you pass in `maxSockets: 100(+)`

For a why explanation...

We default to `connection: close` when there is no `agent` passed in to work around a bug in node core when we set `agent: false`. We default to setting `agent: false` to begin with as it enables the operating system itself to handle the number of sockets that get opened.

**Comment by jcrugzz** [comment]
Marked as FAQ and closing. Let me know if there are any more questions on this.

**Comment by voronianski** [comment]
@jcrugzz could you help with the right place to add the agent? 

From the docs I see that it's used in `http.request` options, but how it could be passed on http create server?

```javascript
var http = require('http');
var proxy = require('http-proxy').createProxy();
var address = require('network-address');
var config = require('../config');

http.createServer(function (req, res) {
    proxy.web(req, res, {
        target: config.router[req.headers.host]
    }, function (e) {
        console.error(e);
        res.writeHead(500, {'Content-Type': 'text/plain'});
        res.end('Something went wrong. Please try again.');
    });
}).listen(80);
console.log('Proxy server started at ' + address());
```

**Comment by jcrugzz** [comment]
@voronianski its one of the options you pass into the `http-proxy` constructor. So you would change the above to...

```js

var http = require('http');
var agent = new http.Agent({ maxSockets: Number.MAX_VALUE });
var proxy = require('http-proxy').createProxy({ agent: agent });
var address = require('network-address');
var config = require('../config');

http.createServer(function (req, res) {
    proxy.web(req, res, {
        target: config.router[req.headers.host]
    }, function (e) {
        console.error(e);
        res.writeHead(500, {'Content-Type': 'text/plain'});
        res.end('Something went wrong. Please try again.');
    });
}).listen(80);
console.log('Proxy server started at ' + address());
```

**Comment by voronianski** [comment]
@jcrugzz thanks!

**Comment by szarouski** [comment]
@jcrugzz, I'm trying to wrap my head around why one would want to specify `maxSockets`? It seems that it is not a `maxSockets` value which is making connection to change to 'keep-alive'. It is enough to just have http.Agent instance. I tried to debug core http module, but stuck on what exactly is causing it to pick keepAlive setting even when it is not set to true on the agent instance. Can you please give me a hint? Thanks.

**Comment by jcrugzz** [comment]
@szarouski this is because the default `maxSockets` value is `5` which is insanely low and not recommended for production use at all. The agent itself is in charge of handling `keep-alive`

**Comment by szarouski** [comment]
Oh I see. It [changed](http://nodejs.org/docs/v0.11.6/api/http.html#http_agent_maxsockets) at v0.11.6 to `Infinity`. It is a bit confusing that agent will maintain keep-alive even if `keepAlive` property was never set and therefor is set by default to `false`.
