### ISSUE TITLE
Cross-domain, cross-port proxying does not work

### ISSUE THREAD

**Issue by jedverity** [nodejitsu/node-http-proxy#768]
If I listen on :8000 and target different.domain:8000 it works fine. But if I listen on :3003 and target different.domain:8000, I get:

    WebSocket connection to '...' failed: Connection closed before receiving a handshake response

I can get it to work by manually modifying `req.headers.host` to have the same port as the target port before sending on to the proxy but isn't there a better way?

**Comment by jcrugzz** [comment]
@jedverity you can use the [`changeOrigin`](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy.js#L43) that is passed when you instantiate the proxy

**Comment by jedverity** [comment]
Excellent thank you @jcrugzz .
