### ISSUE TITLE
Proxy local ip

### ISSUE THREAD

**Issue by btmdave** [nodejitsu/node-http-proxy#771]
Is there a way to proxy a server running on another local IP instead of using http? It seems to be a bit of a performance implication.

Thank you

**Comment by jcrugzz** [comment]
@btmdave I'm not sure if I understand your question, could you give an example ideally with code? You can proxy to a local IP address (usually localhost) listening on a different port with no issue. If you are trying to proxy over a protocol that is not `http`, you have found the wrong module.

**Comment by btmdave** [comment]
Sorry, my mistake, local ip works fine.
