### ISSUE TITLE
x-forwarded-proto incorrectly set to 'http' on node 0.12.0

### ISSUE THREAD

**Issue by jphaas** [nodejitsu/node-http-proxy#772]
I upgraded node to 0.12.0 and it looks like the https detection logic isn't working any more.

It looks like the issue is on line 70 of /lib/http-proxy/passes/web-incoming.js: req.connection.pair is evaluating to undefined even though it's an https connection.

I'm creating a server like so:

    https_server = https.createServer my_https_options, (req, res) ->
        proxy.web req, res, {
            xfwd: true
            target: {host: 'localhost', port: configuration.port}
        }

    https_server.listen configuration.ssl_port

**Comment by jcrugzz** [comment]
@jphaas Ill see what the right thing to do is now and start testing on 0.12 so we can see that status. Thanks for the report

**Comment by feross** [comment]
This is confirmed on iojs 1.5.1 as well.

**Comment by feross** [comment]
Just sent a PR to fix this issue: https://github.com/nodejitsu/node-http-proxy/pull/789
