### ISSUE TITLE
self-signed certs don't need to be avoided - they can be done right.

### ISSUE THREAD

**Issue by coolaj86** [nodejitsu/node-http-proxy#780]
If privacy is important during transit, then it is important during transit the whole way through (many a hack has been accomplished from the inside of "safe" networks).

The problem with self-signed certs is that most tutorials are incorrect - the blind leading the blind (I've written one of those myself back in the day).

However, I'd like to suggest linking to a working example of self-signed certs rather than discouraging them (because it's hard to justify a $30 cert on the "inside" of the network).

Here's an example I wrote, complete with article and screencast: https://github.com/coolaj86/nodejs-ssl-example

Or perhaps this example would be better: https://github.com/coolaj86/nodejs-self-signed-certificate-example

**Comment by EvgeniGordeev** [comment]
+1.

**Comment by jcrugzz** [comment]
Self signed certs can be used without issue when using the `secure: false` option. Will definitely take a pull-request with docs if you feel strongly about it :).

**Comment by coolaj86** [comment]
They can be used without issue using `secure: true`. It would be a very bad idea to do `secure: false` - kinda defeats the point of using certificates.

**Comment by jcrugzz** [comment]
@coolaj86 Sure. Again a PR is more than welcome :). Closing as `docs`
