### ISSUE TITLE
Async proxy 

### ISSUE THREAD

**Issue by kovacspeter** [nodejitsu/node-http-proxy#802]
I need to do some requests(eg. authorization) before proxying. Is there some api support as was before ?

<a href ='https://github.com/nodejitsu/node-http-proxy/issues/168'>https://github.com/nodejitsu/node-http-proxy/issues/168</a>
<code>proxy.buffer(req)</code>

Thanks.

**Comment by jcrugzz** [comment]
@kovacspeter Since node `0.10.x` buffering is built into streams so this is no longer necessary. You can do any async call before calling `proxy.web` as long as you don't need to read data from the `req` itself.

**Comment by kovacspeter** [comment]
I do need to read data request body. I use bodyParser + restreamer + connect as shown in example <a href='https://github.com/nodejitsu/node-http-proxy/blob/master/examples/middleware/bodyDecoder-middleware.js'>Here</a>. Can you give me hand here and advise me how to do it?

**Comment by kovacspeter** [comment]
Its easy, you just need to restream it again.

**Comment by gvp-adityapraveen** [comment]
@kovacspeter  i am in a similar situation can you please post working code , i didn't quite understood restreaming it again part . Any help would be greatly appreciated
