### ISSUE TITLE
Cannot read property 'prototype' of undefined error

### ISSUE THREAD

**Issue by mupakoz** [nodejitsu/node-http-proxy#809]
Because of eventemmiter version change to 1.0.0 the "Cannot read property 'prototype' of undefined" error pops up when trying to run grunt build or grunt -v on project your library. Here is the listing:

```
$ grunt -v
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>>     at Object.exports.inherits (util.js:556:43)
>>     at Object.<anonymous> (...\node_modules\grunt-connect-proxy\node_modules\http-proxy\lib\http-proxy\index.js:106:17)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (...\node_modules\grunt-connect-proxy\node_modules\http-proxy\lib\http-proxy.js:4:17)
>>     at Module._compile (module.js:456:26)
```

http-proxy with eventemmiter version 0.1.6 works fine. As you can see I'm using grunt-connect-proxy which is using the http-proxy library, but as I mentioned eariler the problem is with eventemmiter3 dependency.

**Comment by Kroid** [comment]
Equal error, http-proxy v.1.1.6.

In gulpfile.js:
```
require('http-proxy');
```

**Comment by mupakoz** [comment]
I am also using 1.1.6 version

**Comment by jondubois** [comment]
Same

**Comment by jondubois** [comment]
Upgrading to 1.11.0 fixed the issue for me without apparent side effects.

**Comment by mupakoz** [comment]
My problem's source was: https://github.com/drewzboto/grunt-connect-proxy/issues/95

**Comment by jcrugzz** [comment]
Glad you guys found a solution!

**Comment by jcrugzz** [comment]
@jondubois this is how semver is supposed to work! :smile:

**Comment by joe-spanning** [comment]
Why wouldn't you tie a specific release version of http-proxy to more precise dependency versions? That would prevent this from happening in the future.

**Comment by jcrugzz** [comment]
@joe-spanning this is currently the case. A point in the past it was not properly versioned which caused this issue.
