### ISSUE TITLE
eventemitter3 causing issue

### ISSUE THREAD

**Issue by cthorner** [nodejitsu/node-http-proxy#810]
I ran into an issue when trying to running grunt-connect-proxy which relies on http-proxy. Looks like http-proxy/index.js has this line:

EE3       = require('eventemitter3').EventEmitter,

Which sets EE3 to undefined. Changing it to this:

EE3       = require('eventemitter3'),

fixed the issue.

**Comment by jcrugzz** [comment]
@cthorner update to newest version which has this fix and has no breaking changes :)

**Comment by cthorner** [comment]
Thanks!
