### ISSUE TITLE
migrating from 3.x to 4.x documentation missing

### ISSUE THREAD

**Issue by neekey** [nodejitsu/node-http-proxy#820]
from the top of guide page: http://mongoosejs.com/docs/guide.html

> from 3.x to 4.x please take a moment to read the [migration guide](http://mongoosejs.com/docs/migration.html).

but the content of "migration guide" starts with:

> Migrating from 2.x to 3.x ...

Very confusing.

**Comment by smazurov** [comment]
what does this have to do with node-http-proxy?

**Comment by neekey** [comment]
Sorry, this is so embarrassing, I opened this issue here carelessly and haven't realized it until now! I'll move it to the mongoose repo LOL
