### ISSUE TITLE
can't include http proxy library

### ISSUE THREAD

**Issue by lhy0512** [nodejitsu/node-http-proxy#822]
I include this library https://github.com/nodejitsu/node-http-proxy to my project. I can run nexe to create my single file successfully, but when I ran the binary file. It gives the following error at the bottom.

I then exclude the module by using the dynamic require technique mentioned in this page https://github.com/crcn/nexe, and put it alongside with the single file, it works then. 

New to node.js. Is it because this is an "native module" so I can't include it? It doesn't look like one.

------------------------------------------------------------------------------------------------------------------------
[root@seludevserver linguo-ui-lite]# ./linguoui.bin
nexe.js:25123
  module.exports.createProxy = function createProxyServer(options) {
                             ^
TypeError: Cannot set property 'createProxy' of undefined
    at Array.call./home/selu/linguo-ui-lite/node_modules/http-proxy/lib/http-proxy.js.http (nexe.js:25123:30)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call./home/selu/linguo-ui-lite/node_modules/http-proxy/index.js../lib/http-proxy (nexe.js:25095:18)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call./home/selu/linguo-ui-lite/app.js.http (nexe.js:52:17)
    at initModule (nexe.js:29:11)
    at Array.forEach (native)
    at nexe.js:39:8

------------------------------------------------------------------------------------------------

**Comment by jcrugzz** [comment]
This is not a bug in `http-proxy`, its a bug in this `nexe` loader you are using. There should never be a case where `module.exports` is `undefined`

**Comment by lhy0512** [comment]
sorry I meant to post this in nexe's git. My bad.
