### ISSUE TITLE
Target response

### ISSUE THREAD

**Issue by poluyanov** [nodejitsu/node-http-proxy#838]
Hi!
How i can get the response body(json) in proxyRes event?

```javascript
	proxy.on('proxyRes', function (proxyRes, req, res) {

	});
```

**Comment by tanaydin** [comment]
Here a little code example for your situation. But don't forget, this gets only if response in clear text. you have to make in unzip if it's zipped etc.

    proxy.on('proxyRes', function (proxyRes, req, res) {
        var chunks = [];
        proxyRes.on('data', function receiveChunks(chunk) {
            chunks.push(chunk);
        });

        // trigger on data end
        proxyRes.on('end', function proxyResponseEnd() {
            // make string from buffer
            var buffer = Buffer.concat(chunks);
            console.log(buffer.toString());
        });
    }

**Comment by Farham0** [comment]
Any idea about req body ?
