### ISSUE TITLE
Ignore path and the trailing slash

### ISSUE THREAD

**Issue by mereghost** [nodejitsu/node-http-proxy#839]
As I need to rewrite the request URL as it does not map perfectly to the applications under the proxy, I've set ignorePath to true.

Then I proceeded to define the target as a full doctored url (a valid URL for my applications), but as in common.js:82 it does not truly ignore the path. It sets it to '/' and them proceeds to append it to target / forward.

Is there any way around that? Is there a better way to do what I need?

**Comment by mereghost** [comment]
Hmmm... the only current way (that I found) to bypass this behavior is rewriting the proxied request path using the callback 'proxyReq'

```javascript
proxy.on('proxyReq', function (proxyReq, req, res, options) {
    proxyReq.path = path;
});
```

**Comment by bdefore** [comment]
thanks @mereghost i was looking for just this. to prepend, you can do i.e. `proxyReq.path = "/api/" + proxyReq.path'. certainly would be nicer if `ignorePath` was better documented.

**Comment by cdl** [comment]
Thanks @mereghost - just ran into this issue myself, but it didn't surface until dealing with proxying requests with query parameters. Glad to see I'm not going insane. :+1:

**Comment by RickWong** [comment]
:+1:

**Comment by darrenmce** [comment]
:+1: `/` appended to end of querystring when using `ignorePath`

**Comment by 75lb** [comment]
i need to rewrite the target path too for the exact same reason (the target URL structure does not match the source URL structure). 

[this appended trailing slash](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/common.js#L91) breaks the ability to rewrite the target path as a specific resource.. could we remove it and update the docs for `ignorePath` stating that, if required, we must manually append our own `target` trailing slash?

**Comment by niclic** [comment]
Apparently resolved by this: https://github.com/nodejitsu/node-http-proxy/pull/934

**Comment by jcrugzz** [comment]
@niclic should be, thanks :)
