### ISSUE TITLE
Nested event bus per specific web request

### ISSUE THREAD

**Issue by h2non** [nodejitsu/node-http-proxy#842]
That could be useful for some scenarios when you have to deal with multiple proxy instances and react to particular states based on the specific proxy request instead of using global event handlers.

I would like to do something like this:
```js
proxy.web(req, res, opts)
  .on('error', handler)
  .on('proxyRes', handler)
```

Is there another way to achieve that?

**Comment by jcrugzz** [comment]
@h2non theres nothing stopping you from making a proxy instance on a per request basis if you wanted to have different handlers based on those particular requests.

**Comment by h2non** [comment]
May be it was my fault explaining this... but actually `proxy.web()` returns `undefined`. How you handle the events for a specific proxy request only. Thanks

**Comment by h2non** [comment]
Creating new instances. All clear.

**Comment by jcrugzz** [comment]
@h2non to be more clear, you would have to instantiate a proxy instance on each request. e.g.

```js
var http = require('http');
var HttpProxy = require('http-proxy');

http.createServer(function (req, res) {
  //
  // Maybe do some checking on the req.url because we might want to reuse this instance for the same
  // routes
  var proxy = new HttpProxy(options)
    .once('error', errorHandler)
    .once('proxyRes', proxyResHandler);

  proxy.web(req, res);

});
```

**Comment by h2non** [comment]
Perfect, thank you!
