### ISSUE TITLE
changeOrigin not in documentation

### ISSUE THREAD

**Issue by Morriz** [nodejitsu/node-http-proxy#851]
This cost me many hours to figure out....I might be stoopid, but more ppl like me could lost valuable time over this.

Why isn't this option enabled by default? It would serve 99% of the use cases out there.

**Comment by jpatters** [comment]
I also just wasted several hours on this. 
+1 for adding it to the docs

**Comment by jcrugzz** [comment]
I will definitely take a pull-request for it :)

**Comment by Morriz** [comment]
Sure. Who will put that extra line in the docs? Last one in line? I will do it when I have the time ;)

**Comment by jpatters** [comment]
I'd do it but I have no idea where it should go. Any suggestions? The readme is kind of all over the place on doesn't really document anything. It just gives examples. Should it be its own example?

**Comment by Morriz** [comment]
Just mention it in the list of options with a short explanation. Thats enough

**Comment by bdefore** [comment]
:+1: also lost quite a bit of time until i found this in the docs. i'm not sure why it's not true by default!

**Comment by kdepp** [comment]
+1, changeOrigin should be defaultly set to true

**Comment by indexzero** [comment]
@bdefore @kdepp that is not the purpose of this issue. It should have been closed with #852. If you feel strongly about `changeOrigin` please open a new issue if one does not exist. 

I am not opposed to it.
