### ISSUE TITLE
on('proxyRes') event being called multiple times

### ISSUE THREAD

**Issue by han4wluc** [nodejitsu/node-http-proxy#854]
Hello, 
I set up a simple proxy server on express and tried to observe the `on('proxyRes')` event. However for some reason the event is being called more times than I expected.
This is `"express": "^4.13.1"` and `"http-proxy": "^1.11.1"`

    var express = require('express');
    var app = express();
    var http = require('http').Server(app);
    var httpProxy = require('http-proxy');
    var proxy = httpProxy.createProxyServer();

    // proxy service
    http.listen(3000, function(){
      console.log('server listening on: 3000');
    });

    app.get('/api/users/:id', function(req, res){
      console.log('');
      proxy.web(req, res, { 
        target: 'http://localhost:8081'
      });
      proxy.on('proxyRes', function (proxyRes, req2, res2) {
        console.log(req.params.id);
      });
    });

    // users service
    var app2 = express();
    var http2 = require('http').Server(app2);
    app2.get('/api/users/:id', function(req, res){
      res.status(200).send();
    });
    http2.listen(8081, function(){
      console.log('server listening on: 8081');
    });

By sending 4 consecutive GET request I expected to get one `on('proxyRes')` event for each request.
    
    curl localhost:3000/api/users/request1
    curl localhost:3000/api/users/request2
    curl localhost:3000/api/users/request3
    curl localhost:3000/api/users/request4

but I got the following log.

    request1

    request1
    request2

    request1
    request2
    request3

    request1
    request2
    request3
    request4

Am I doing something wrong? I tried to add a `proxy.close()` at the end of the code, but it made no difference.

**Comment by acanimal** [comment]
You must register the `proxy.on('proxyRes'...)` outside the `app.get(...`, otherwise you are registering multiple listeners.

**Comment by han4wluc** [comment]
I see, you are right. Thank you.
