### ISSUE TITLE
Proxy issue when no forward slash is provided

### ISSUE THREAD

**Issue by alansouzati** [nodejitsu/node-http-proxy#857]
Great job with node-http-proxy!

I'm was able to successfully integrate that to my project, but there is a scenario that I'm not sure how to fix.

My current server is like this:

```
var express = require('express');
var httpProxy = require('http-proxy');
var app = express();
...
var proxy = httpProxy.createProxyServer({
  target: 'ws://localhost:8010',
  ws: true
});

app.use('/sample-app/', function(req, res){
  proxy.web(req, res, { target: 'http://localhost:8010/sample-app' });
});
...
var server = http.createServer(app).listen(8000);
```

If my path is `http://localhost:8000/sample-app/` it does work fine. But, if we remove the forward slash from the path it fails (`http://localhost:8000/sample-app`). When I look at the browser console, all the requests from 8010 are actually sent to 8000.

Any idea how to fix that? Thanks!

**Comment by keithmo** [comment]
I do something like this:

```
var mountpoint = '/sample-app';

app.use(mountpoint, function(req, res) {
    if (req.originalUrl === mountpoint) {
        res.redirect(301, req.originalUrl + '/');
    } else {
        proxy.web(req, res, ...);
    }
});
```

**Comment by alansouzati** [comment]
Sweet, thank you so much @keithmo!

**Comment by acanimal** [comment]
Hi @alansouzati 
see the `strict` property in the router configuration on Express http://expressjs.com/api.html#router

By default `/sample-app/` and `/sample-app` are handled as different resources.

**Comment by keithmo** [comment]
Thanks for the info, @acanimal -- I was not aware of the strict property on the router.

**Comment by alansouzati** [comment]
Thanks for the insight @acanimal !

I haven't had a chance to test this entirely, but adding strict option in my server did not work. Maybe it is also necessary to add strict option inside proxy server as well?

I will try this soon and will update you guys!
