### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by jaumard** [nodejitsu/node-http-proxy#861]
Hi,

I'm trying to use this proxy to redirect domain and subdomain to the correct server. I have 2 sails.js server with http and websocket so I have make a proxy like this : 

```
var http = require('http'),
    httpProxy = require('http-proxy'),
    proxy = httpProxy.createProxyServer({}),
    url = require('url');

var server = http.createServer(function(req, res) {
    var hostname = req.headers.host.split(":")[0];

    switch(hostname)
    {
        case 'domain.com':
            proxy.web(req, res, { target: 'http://localhost:8080' });
            break;
        case 'dev.domain.com':
            proxy.web(req, res, { target: 'http://localhost:8081' });
            break;
        default:
            proxy.web(req, res, { target: 'http://localhost:8080' });
    }
});


//
// Listen to the `upgrade` event and proxy the
// WebSocket requests as well.
//
server.on('upgrade', function (req, socket, head)
{
        var hostname = req.headers.host.split(":")[0];
switch(hostname)
    {
        case 'domain.com':
            proxy.ws(req, socket, { target: 'ws://localhost:8080' });
            break;
        case 'dev.domain.com':
            proxy.ws(req, socket, { target: 'ws://localhost:8081' });
            break;
        default:
            proxy.ws(req, socket, { target: 'ws://localhost:8080' });
    }
});

server.listen(80, function() {
    console.log('proxy listening on port 80');
});
```

But after some request I have this error : 
```
/var/www/default/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketCloseListener (_http_client.js:247:23)
    at Socket.emit (events.js:129:20)
    at TCP.close (net.js:485:12)
```

How can I fix this ?

**Comment by jcrugzz** [comment]
You need to listen for errors on your `proxy` instance and return an error
to the requester when it happens. See [`proxy-server`](
https://github.com/jcrugzz/proxy-server/blob/master/index.js#L55-L67) for
an example.

On Fri, Aug 7, 2015 at 4:50 AM, Jaumard <notifications@github.com> wrote:

> Hi,
>
> I'm trying to use this proxy to redirect domain and subdomain to the
> correct server. I have 2 sails.js server with http and websocket so I have
> make a proxy like this :
>
> var http = require('http'),
>     httpProxy = require('http-proxy'),
>     proxy = httpProxy.createProxyServer({}),
>     url = require('url');
>
> var server = http.createServer(function(req, res) {
>     var hostname = req.headers.host.split(":")[0];
>
>     switch(hostname)
>     {
>         case 'domain.com':
>             proxy.web(req, res, { target: 'http://localhost:8080' });
>             break;
>         case 'dev.domain.com':
>             proxy.web(req, res, { target: 'http://localhost:8081' });
>             break;
>         default:
>             proxy.web(req, res, { target: 'http://localhost:8080' });
>     }
> });
>
>
> //
> // Listen to the `upgrade` event and proxy the
> // WebSocket requests as well.
> //
> server.on('upgrade', function (req, socket, head)
> {
>         var hostname = req.headers.host.split(":")[0];
> switch(hostname)
>     {
>         case 'domain.com':
>             proxy.ws(req, socket, { target: 'ws://localhost:8080' });
>             break;
>         case 'dev.domain.com':
>             proxy.ws(req, socket, { target: 'ws://localhost:8081' });
>             break;
>         default:
>             proxy.ws(req, socket, { target: 'ws://localhost:8080' });
>     }
> });
>
> server.listen(80, function() {
>     console.log('proxy listening on port 80');
> });
>
> But after some request I have this error :
>
> /var/www/default/node_modules/http-proxy/lib/http-proxy/index.js:119
>     throw err;
>           ^
> Error: socket hang up
>     at createHangUpError (_http_client.js:215:15)
>     at Socket.socketCloseListener (_http_client.js:247:23)
>     at Socket.emit (events.js:129:20)
>     at TCP.close (net.js:485:12)
>
> How can I fix this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejitsu/node-http-proxy/issues/861>.
>



-- 
Jarrett Cruger
Software Engineer at GoDaddy <https://www.godaddy.com/> Inc.
