### ISSUE TITLE
Example for completely transparent http proxy/forwarder with zero business logic or req/res modification.

### ISSUE THREAD

**Issue by iMerica** [nodejitsu/node-http-proxy#864]
Hey guys,

Is there an example of a completely dumb/transparent/logic-less http proxy using `node-http-proxy` that does not make assumptions about [headers](https://github.com/nodejitsu/node-http-proxy/blob/master/examples/http/forward-proxy.js#L47) and does not alter [response bodies](https://github.com/nodejitsu/node-http-proxy/blob/master/examples/http/forward-proxy.js#L48)?

I want a 100% pure and stateless proxy where the only thing that is "variable" is the host URL where the requests get sent to and respond from.

It's a pretty simple scenario
```
[CLIENT]  
Headers, Method, Payload, Host + URI
                    
↑   ↓

[SUPER DUMB PROXY] 

          - Sends same exact same request except it's going to the target server URL.
↑   ↓    - Respond with the same exact response data except for server URL.
          - Client has no idea what's going on.

[Target Server] 
Responds as normal
```

All the [examples](https://github.com/nodejitsu/node-http-proxy/tree/master/examples) appear to do more than this.

Kind regards,

Michael

**Comment by acanimal** [comment]
Maybe you could be interested on: http://stackoverflow.com/questions/20351637/how-to-create-a-simple-http-proxy-in-node-js or http://www.catonmat.net/http-proxy-in-nodejs/.

**Comment by iMerica** [comment]
Thanks @acanimal !

For anyone coming back to this issue, I was able to achieve this with the following:

```javascript
var http = require('http');

http.createServer(onRequest).listen(3000);

function onRequest(client_req, client_res) {
  console.log('serve: ' + client_req.url);

  var options = {
    hostname: 'TARGET_SERVER_HOSTNAME',
    port: 80,
    path: client_req.url,
    method: 'GET'
  };

  var proxy = http.request(options, function (res) {
    res.pipe(client_res, {
      end: true
    });
  });

  client_req.pipe(proxy, {
    end: true
  });
}
```
