### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by morrismukiri** [nodejitsu/node-http-proxy#884]
I keep getting socket hangup error on a meteor app.
Here's the error I keep getting 

```
C:\Users\Administrator\AppData\Local\.meteor\packages\nourharidy_ssl\0.2.2\npm\node_modules\http-proxy\lib\http-proxy\index.js:119
     throw err;
           ^
 Error: socket hang up
     at createHangUpError (http.js:1477:15)
     at Socket.socketCloseListener (http.js:1527:23)
     at Socket.emit (events.js:95:17)
     at TCP.close (net.js:466:12)
```

**Comment by mehrdadarvin** [comment]
Getting the same error. Not really sure what's happening or why. I noticed it happening when I set --ignore-ssl-errors= true for phantom.

**Comment by sylido** [comment]
Having the same issue, using it on a meteor server that makes use of this package. Any suggestions ?

**Comment by jcrugzz** [comment]
@morrismukiri @sylido the meteor package using this is not handling errros. They must listen on the `error` event or use the callback api to handle errors. See [here](https://github.com/jcrugzz/proxy-server/blob/master/index.js#L29-L29) for an example.

**Comment by sylido** [comment]
Thanks jcruggz I found the solution after searching here, but that just handles the error right ? Is that enough or is there something else that must be done to prevent the actual socket hang up from happening.

**Comment by jcrugzz** [comment]
@sylido socket hangup is something node emits internally when a socket is no longer usable or something happens. Could be a symptom of a single server handling too much but its hard to say. Best you can do when it happens is just tell the caller it errored

**Comment by jasonfutch** [comment]
We are having the same issue and can recreate very easily when running latency tests. This is caused when the requesting client (browser) is no available to receive the response.

Steps to recreate.
1. Create a proxy to another endpoint that has a latency and longer running process on it. (3 sec timeout in the response works)
2. Call the proxy from the webpage and refresh before you get a response back, the "socket hang up" will happen every time.

In our situation we are only using this proxy during local development and using nginx for production.

**Comment by sunlee-newyork** [comment]
Same issue here for local server - using package called SSLProxy which depends on http-proxy I believe. Ever since I installed it, when Meteor triggers a rebuild after every file save the client socket connection seems to break and throw this hangup error. Meteor then triggers a second rebuild because of the error and I have to wait until it's finished to reload the browser and make a whole new socket connection.

**Comment by guguji5** [comment]
I move the `app.use(bodyParser())` after the proxy middleware just like below 

```
// middleware
app.use(proxy('/flow', {
  target: 'http://example.com',    
  changeOrigin: true,
  rewrite: path => {
    return path.replace('/dicloud/feapi/','/')
  },
  logs: true
}))

app.use(bodyParser()) // must behind the proxy
```

and fix it.
