### ISSUE TITLE
Impossible to ignore proxy path prefix

### ISSUE THREAD

**Issue by borNfreee** [nodejitsu/node-http-proxy#887]
Hi,

I need to proxy requests from `/api` to the root of other site: `http://test.com`:

`/api/users` -> `http://test.com/users`
`/api/users/1` -> `http://test.com/users/1`

But all my requests lead to `http://test.com/api/*`
How to ignore `/api` prefix but not to ignore other path?
When I use `ignorePath` settings all my requests lead to `http://test.com`.

Config:

```js
server.middleware = proxyMiddleware('/api', {target: 'http://test.com', proxyHost: 'test.com'});
```

**Comment by joeyespo** [comment]
Just ran into this too :+1: 

@borNfreee Find a suitable workaround since you posted this?

**Comment by sequoiar** [comment]
@borNfreee you need use http-proxy with middleware like express.js or connect.js

**Comment by chimurai** [comment]
@borNfreee's question has been answered in: https://github.com/chimurai/http-proxy-middleware/issues/31#issuecomment-143770591

**Comment by borNfreee** [comment]
Thanks @chimurai You are right

**Comment by mik01aj** [comment]
I have the same problem, but I can't use the @chimurai's solution because I don't use the middleware. I use the [webpack dev server](https://webpack.github.io/docs/webpack-dev-server.html).

Would this be possible with just `node-http-proxy` options? Or do I need to request the feature from webpack guys?

**Comment by chimurai** [comment]
@mik01aj 
`node-http-proxy` doesn't offer path rewrite through options;
It's some sugar added by `http-proxy-middleware`.

Good news for you perhaps, HPM is now being used by `webpack-dev-server`.
https://github.com/webpack/webpack-dev-server/pull/359

It is not push to npm yet, so you'll have to wait a bit...
`pathRewrite` option will be available there too (soon).

**Comment by mik01aj** [comment]
That's some very good news, thanks!
