### ISSUE TITLE
Error events not firing

### ISSUE THREAD

**Issue by super-cache-money** [nodejitsu/node-http-proxy#900]
If, after being proxied to, my backend express server does: `res.status(403).send('Not logged in')`, an error event is not fired on the front facing server, from which the proxy originates. 

I'm listening for error events on the front facing server like this:

    var app = new Express();
    
    var proxy = httpProxy.createProxyServer({
      target: 'http://localhost:3030',
      ws: true
    });
    
    app.use('/to-backend', function(req, res) {
      proxy.web(req, res);
    });
    
    proxy.on('error', function(error, req, res){
      console.log('Error from backend',error);
    });

Why is no error event fired? Am I misunderstanding what qualifies as an error response from the proxy destination?

**Comment by jcrugzz** [comment]
@super-cache-money an error event wont fire because the backend express server was able to respond correctly. An error only happens when we are unable to proxy to the backend server.
