### ISSUE TITLE
How to use a process stdin as target?

### ISSUE THREAD

**Issue by piranna** [nodejitsu/node-http-proxy#911]
Since the `http` module accept to listen for incomming connections on any object with a `fd` file descriptor field like `stdin` I would like to send the request there, but `http-proxy` target requires to be "a string parseable by the `url` module" (although I have seen in several place it to be defined as an object). Is there any way to define the `target` as anything other than an url, like a `child_process.stdin` pipe/stream or a domain socket? Since both process (proxy and web server) will run on the same machine there's no need to use an url and will be faster and more secure...

**Comment by jcrugzz** [comment]
@piranna this is no longer `http-proxy`ing at that point so it is out of the scope of this module. you are better off using something like [`hyperquest`]('https://github.com/substack/hyperquest) and piping that directly to `stdin` of the child process. I wrote [`strong-parent`](https://github.com/jcrugzz/strong-parent) and [`strong-child`](https://github.com/jcrugzz/strong-child) to deal with situations similar to this.

**Comment by piranna** [comment]
> @piranna this is no longer http-proxying at that point so it is out of
the scope of this module.

Are you talking about the fact of using stdin, isn't? I have been thinking
that maybe this would be a somewhat complicated solution, so I'm going the
web server to start on a random port and notify it to the proxy, so I can
be able to still using http-proxy while being secure since the port is
unpredictable. Do you think is it a good idea?
