### ISSUE TITLE
hostRewrite doesn't work

### ISSUE THREAD

**Issue by yejijie** [nodejitsu/node-http-proxy#913]
I use node-http-proxy to proxy Google，there is a problem with redirection(302), but when I add the Options hostRewrite, the proxy does not work too. When I check the source code，I find the following code:https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-outgoing.js#L49
```
function setRedirectHostRewrite(req, res, proxyRes, options) {
    if ((options.hostRewrite || options.autoRewrite || options.protocolRewrite)
        && proxyRes.headers['location']
        && redirectRegex.test(proxyRes.statusCode)) {
      var target = url.parse(options.target);
      var u = url.parse(proxyRes.headers['location']);

      // make sure the redirected host matches the target host before rewriting
      if (target.host != u.host) {
        return;
      }

      if (options.hostRewrite) {
        u.host = options.hostRewrite;
      } else if (options.autoRewrite) {
        u.host = req.headers['host'];
      }
      if (options.protocolRewrite) {
        u.protocol = options.protocolRewrite;
      }

      proxyRes.headers['location'] = u.format();
    }
  }
```
why should we make sure the redirected host matches the target host before rewriting? 
For example, if I am from China, when i curl the google `curl www.google.com`, Google will redirect to www.google.com.hk; if i am from  Japan, when I curl the google, Google will redirect to www.google.co.jp.
Because the redirected host doesn't match the target host, the hostRewrite doesn't work. 
And when I remove the following code:
```
// make sure the redirected host matches the target host before rewriting
      if (target.host != u.host) {
        return;
      }
```
the proxy works.
Any idea please?

**Comment by chimurai** [comment]
You'll need to set `changeOrigin` to `true`.
