### ISSUE TITLE
http/2 proxy?

### ISSUE THREAD

**Issue by m1stegmann** [nodejitsu/node-http-proxy#920]
Is it possible to build a http/2 proxy and fordard the requests to a normal https server? Example please :-)

**Comment by indexzero** [comment]
Using http/2 is not currently possible. Pull-request for this support would be welcome. I believe the SPDY module from @indutny might support http/2 now.

**Comment by jcrugzz** [comment]
@indexzero @m1stegmann i had an exchange with @indutny that it just requires passing an agent from his `spdy` module which supports `http2` for this to work

**Comment by aaronmaturen** [comment]
I had a working version of this project with HTTP2 for node >= 0.12.0 here #919 unfortunately node 0.10 isn't supported by the HTTP2 module.
