### ISSUE TITLE
cert_has_expired

### ISSUE THREAD

**Issue by vaibhavatul47** [nodejitsu/node-http-proxy#925]
Hi,
The proxy server is throwing error "CERT_HAS_EXPIRED" for ssl. How it can be solved?

**Comment by caioquirino** [comment]
I'm Getting this problem too:
Error: certificate has expired

**Comment by caioquirino** [comment]
I need a form to send the parameter rejectUnauthorized: false to https request. Does anyone know?

**Comment by indexzero** [comment]
You need a new certificate.
