### ISSUE TITLE
Blocked by Websense

### ISSUE THREAD

**Issue by zardoz** [nodejitsu/node-http-proxy#937]
Are you aware that your product and this page, is being actively blocked by Websense?

**Comment by jcrugzz** [comment]
This is an open source project found on github, not a product. Either way, this is not something in our control as maintainers of open source software. I am curious to the nature of this being "blocked" as i am not familiar with Websense. Please feel free to respond but closing as this is not a bug in the project

**Comment by zardoz** [comment]
Sorry bad terminology. I was trying to look at this link [https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/ws-incoming.js] on your repo yesterday, We use NodeJS in production, We have an issue with reverse proxy for websockets.  Have since realised it's actually our IIS / ARR infrastructure, go figure! Anyway we use Websense as a company-wide proxy, I've attached the report. It doesn't sit right with me, there may be truth to it but I'll let you find that out. Firstly they have said this resource is about proxy avoidance, which it's not, secondly that there are malicious links on the resource (your repo), in their words:

"A site lookup -
Master Database v7.x: Proxy Avoidance
Real-time Category: Proxy Avoidance 
Both investigations have confirmed that the URL is a in the category Proxy Avoidance. This category actually falls under the Risk Classes "Legal Liability" and "Security Risk". By default, this category will be blocked even if a site is added to an exception or a custom category to protect you and your environment."

![ws1](https://cloud.githubusercontent.com/assets/48041/12454356/08692b46-bf8f-11e5-8cdc-8e1403f8ca9d.PNG)
![ws2](https://cloud.githubusercontent.com/assets/48041/12454357/08afac9c-bf8f-11e5-8700-6a0d7a65b5d9.PNG)


I just wanted to give you a heads up on this, so that you can investigate, and resolve this if you so wish to.

Yes this is not a bug

**Comment by pyper** [comment]
They are likely blocking based on keywords in the URL.  Try visiting other URLs with similar keywords like “proxy”, “http”, “incoming”, “http-proxy”, etc.

**Comment by zardoz** [comment]
I have, many and this was not the case....
