### ISSUE TITLE
Do not use "Transfer-Encoding: chunked" header for proxied DELETE requests (again)

### ISSUE THREAD

**Issue by Turbo87** [nodejitsu/node-http-proxy#960]
This issue is related to PR #373 where this exact bug was already fixed by a89e2f2, but then later apparently introduced again by 8663ac1.

The actual problem is that `DELETE` requests with both `Content-Length: 0` and `Transfer-Encoding: chunked` are illegal and are being rejected by some servers (in this case nodejs since v0.10.42). If the incoming request only has the `Transfer-Encoding` header the proxy will somehow automatically set the `Content-Length` header to `0` but won't remove the encoding header which leads to this issue.

**Comment by jcrugzz** [comment]
@Turbo87 looks like this was lost in translation when the rewrite happened. I'd love PR for this :+1:. Definitely a good first contributor issue :)
