### ISSUE TITLE
Basic reverse proxy doesn't work

### ISSUE THREAD

**Issue by DominicTobias** [nodejitsu/node-http-proxy#963]
Hi, maybe I'm not understanding the purpose of this library correctly but it does mention that it can be used for reverse proxies. I posted this on SO but didn't get any answers, it must be something I am not fundamentally understanding:

```js
const http = require('http');
const httpProxy = require('http-proxy');

const targetUrl = 'http://www.google.co.uk';

const proxy = httpProxy.createProxyServer({
	target: targetUrl
});

http.createServer(function (req, res) {

    proxy.web(req, res);

}).listen(6622);
```

For example I would expect http://localhost:6622/images/nav_logo242.png to proxy to http://www.google.co.uk/images/nav_logo242.png instead of returning a 404 not found.

I thought maybe I need to manually collect the data, but the response for these valid resource requests is 404, so the `BODY` is `<html><body><h1>404 Not Found</h1></body></html>`:

```js
proxy.on('proxyRes', function(proxyRes, req, res) {
	proxyRes.on('data', function (chunk) {
		console.log('BODY: ' + chunk);
	});
	proxyRes.on('error', function (e) {
		console.log('error', e);
	});
	proxyRes.on('end', function () {
		console.log('end', arguments);
	});
});
```

Thanks.

**Comment by DominicTobias** [comment]
It turns out this was failing as it needed a `Host` header:

```js
proxy.on('proxyReq', function(proxyReq, req, res, options) {
    proxyReq.setHeader('Host', targetHost);
});
```

**Comment by pyper** [comment]
@DominicTobias I know this is closed, but there is a setting for that.  If you set “changeOrigin” to true it will automatically change the host header to the upstream servers for you.

**Comment by DominicTobias** [comment]
@pyper ah that's nice thanks
