### ISSUE TITLE
Modifying The Stream Of  A Websocket

### ISSUE THREAD

**Issue by Lull3rSkat3r** [nodejitsu/node-http-proxy#972]
[We](https://github.com/jupyter-incubator/dashboards_server) have a [requirement](https://github.com/jupyter-incubator/dashboards_server/issues/94) where data being proxied through a websocket needs to be transformed. I have implemented a [`Transform`](https://nodejs.org/api/stream.html#stream_class_stream_transform) stream that I would like place between the pipe of my socket and the proxied socket.

I have a simplified example of what my scenario is [here](https://gist.github.com/Lull3rSkat3r/4a33589e6121525ecb63). I am looking to see if there is a known way to achieve what I am trying to do.

**Comment by johngeorgewright** [comment]
I'm trying to do something similar. Did you have any luck?

**Comment by Lull3rSkat3r** [comment]
@johngeorgewright we ended up restructuring our code and didn't need this.
