### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by roccomuso** [nodejitsu/node-http-proxy#988]
Is node-http-proxy ready for production?
Someone using it successfully?

**Comment by jcrugzz** [comment]
@roccomuso yes, we've used this in production for many years.

**Comment by roccomuso** [comment]
@jcrugzz even as load balancer? a lot of people suggest tools like HAProxy or nginx.. But i'd like to have a full node.js stack.

**Comment by jcrugzz** [comment]
@roccomuso HAProxy or nginx will be a more performant load balancer. HAProxy being the most performant. The advantage you get with `node-http-proxy` is the ability to write a dynamic load balancer very quickly that performs well. It wont be the fastest as previously stated but it depends if that matters for your application.

**Comment by jcrugzz** [comment]
For more context, we used it in production at nodejitsu for 5+ years, and it is used in a production application @godaddy as well. Figure out if its the right tool. Its at least a good place to start for getting things up and running.

**Comment by roccomuso** [comment]
@jcrugzz Thank you for pointing this out. ;) What i need is in fact a dynamic load balancer. Speed is not an essential requirement for my app.

**Comment by tomcanham** [comment]
Since I can't make it not freak out on even the simplest of proxy situations (ie, proxy all localhost:3000 to localhost:3001 -- no SSL, no custom logic, and the same curl request works against localhost:3001 but causes node-http-proxy to explode violently), I'm going to say... no.

**Comment by tomcanham** [comment]
Lest you think I'm just a Github hater, here's the *entirety* of my node-http-proxy code:

`var http = require('http'),
    httpProxy = require('http-proxy');


httpProxy.createProxyServer({target:'http://localhost:3001'}).listen(3000);`

And here's my curl request for a JWT from my auth server:

`curl -X POST -H "Content-Type: application/json" -d '{"username": "baz", "password": "bat"}' http://localhost:3000/api/v1/token`

This produces this "production ready" response:

`Toms-MacBook-Pro:bouncer tomc$ node index
/Users/tomc/src/ROUS/bouncer/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
    ^

Error: getaddrinfo ENOTFOUND localhost localhost:3001
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
Talbots-MacBook-Pro:bouncer tomc$ node index
/Users/tomc/src/ROUS/bouncer/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;`

Whereas this:

`curl -X POST -H "Content-Type: application/json" -d '{"username": "baz", "password": "bat"}' http://localhost:3001/api/v1/token`

(note the port change)

...produces a slightly more nice result:

`{"message":"Signed in successfully.","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7Il9pZCI6ImFjY2M3YjY5ZjZhYzVkODA4MjliN2E1NDAyMTE3ZTQ4IiwiX3JldiI6IjEtZGE1YzJjNDQwYzIxMDdhY2UxMWRkYTMyODRmOTVhYzUiLCJ1c2VybmFtZSI6ImJheiIsImRvY1R5cGUiOiJ1c2VyIiwicm9sZXMiOlsicHVibGljIiwiYXNzZXQucmVhZCIsInByb3Bvc2FsLnJlYWQiLCJhZG1pbiJdfSwiaWF0IjoxNDYwNjQ3MzE4LCJleHAiOjE0NjA3MzM3MTh9.k7HDGiKPyw4f7yF08a_bpvEdjNlU7pb3oK3wtpohLYE","user":{"_id":"accc7b69f6ac5d80829b7a5402117e48","_rev":"1-da5c2c440c2107ace11dda3284f95ac5","username":"baz","docType":"user","roles":["public","asset.read","proposal.read","admin"]}}`

So again -- I'm going to go with, no. It's not production ready. I could debug it, but then again, I could just cobble together my own "reverse proxying" with Express and isomorphic-fetch.

**Comment by indexzero** [comment]
@jcrugzz going to mark this issue as resolved since @roccomuso's original question appears to have been answered. 
 
@tomcanham have you tried other targets besides `localhost`? Like `127.0.0.1`? You are getting a DNS lookup error for `localhost` (that's what `Error: getaddrinfo ENOTFOUND localhost` indicates) so it may be configured in a non-standard way on your development machine.

On standard setups in production you'd be using a DNS target that is known to be valid and/or proxying directly to an IP address depending on how you choose to configure the actors in your proxy-based system. I confirmed that the simple example in the `README`:

``` js
var http = require('http'),
    httpProxy = require('http-proxy');
//
// Create your proxy server and set the target in the options.
//
httpProxy.createProxyServer({target:'http://localhost:9000'}).listen(8000); // See (†)

//
// Create your target server
//
http.createServer(function (req, res) {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.write('request successfully proxied!' + '\n' + JSON.stringify(req.headers, true, 2));
  res.end();
}).listen(9000);
```

Works just fine on my machine (it also works in Travis and in a few VMs). All of which are running the latest Node LTS version.

```
node proxy.example.js
$ curl http://localhost:9000
request successfully proxied!
{
  "host": "localhost:9000",
  "user-agent": "curl/7.43.0",
  "accept": "*/*"
}

$ curl http://localhost:8000
request successfully proxied!
{
  "accept": "*/*",
  "user-agent": "curl/7.43.0",
  "host": "localhost:8000",
  "connection": "close"
}
```

Hope that helps! A PR to our docs outlining what was different about your system so that others can avoid this pitfall in the future would be most welcome.
