### ISSUE TITLE
jsessionid won't store in browser

### ISSUE THREAD

**Issue by adi518** [nodejitsu/node-http-proxy#993]
Hi,

I have the following setup:

Localhost Express (LAN machine #1) -> Localhost Proxy (LAN machine #1) -> Servlet (LAN machine #2).

Servlet is including a Jsessionid cookie in it's response header, which I'm able to modify and receive on the response header of Localhost Express, but for some reason won't store under browser resources. Any ideas?

Thanks.

**Comment by whampop** [comment]
I'm having trouble with the same issue, did you find a work around? The set-cookie header comes back with the JSESSIONID, but the browser doesnt retain it.

**Comment by adi518** [comment]
Yes, the solution was just under my nose. It had nothing to do with node-proxy inner workings. In my case I was making a call from a localized domain (as depicted above) to another localized domain (but a different port of course, because by default Node server listens to all domains assigned to loop-back in your hosts file), which was the proxy server. The mistake was not making the call from the same localized domain (that of Express). So what happened is, the proxy returned the cookie and the browser saved it under the domain name I allocated for it.

To make it easier to understand:
I had an Ajax call going from site.com -> proxy.com:81. The Jsessionid cookie was then saved under the wrong domain, namely proxy.com. I use Chrome, so checking where the cookie was saved was super easy, by browsing to: chrome://settings/cookies.

**Mind you also must specify 'withCredentials" to your Ajax/XHR call, otherwise it won't grant the response to save the cookie.**

**Comment by whampop** [comment]
Thanks!

 For anyone else who stumbles across this issue, I didn't have the same setup,

 -> http://localhost -> proxy -> https://realserver.com, 

In my case the cookie had the Secure flag, so although JSESSIONID was stored @localhost, it was not being sent in subsequent requests because I didnt use the https:// by setting the https property on the webpack-dev-server config.
